<?php
/**
 * Innoexts
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the InnoExts Commercial License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://innoexts.com/commercial-license-agreement
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@innoexts.com so we can send you a copy immediately.
 * 
 * @category    Innoexts
 * @package     Innoexts_WarehousePlusEnterprise
 * @copyright   Copyright (c) 2014 Innoexts (http://www.innoexts.com)
 * @license     http://innoexts.com/commercial-license-agreement  InnoExts Commercial License
 */
?>

<!-- Warehouse -->
<?php $helper                       = $this->helper('warehouse') ?>
<?php $orderHelper                  = $helper->getOrderHelper() ?>
<?php $config                       = $helper->getConfig() ?>
<!-- End Warehouse -->

<?php $_order = $this->getOrder() ?>
<div class="order-page">
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
    
    <!-- Warehouse -->
    <?php if ($orderHelper->isPendingPayment($_order)) : ?>
    <span class="separator">|</span>
    <a href="<?php echo $orderHelper->getMakePaymentUrl($_order) ?>" class="link-make-payment" onclick="this.target='_blank';"><?php echo $helper->__('Make Payment') ?></a>
    <?php endif; ?>
    <!-- End Warehouse -->
    
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul>
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><strong><?php echo $_link->getLabel() ?></strong></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>

<!-- Warehouse -->
<?php if ($config->isInformationVisible()) : ?>
<p class="order-warehouse">
    <?php echo $helper->__('Order Warehouse: ') ?>
    <?php if ($_order->isMultipleWarehouse()) : ?>
    <?php echo implode($helper->__(', '), $_order->getWarehouseTitles()) ?>
    <?php elseif ($_order->getWarehouse()) : ?>
    <?php echo $_order->getWarehouseTitle() ?>
    <?php else : ?>
    <?php echo $helper->__('No warehouse') ?>
    <?php endif ?>
</p>
<?php endif ?>
<!-- End Warehouse -->

<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set">
    <div class="col-1">
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('Shipping Address') ?></h2>
            <address class="box-content"><?php echo $_order->getShippingAddress()->format('html') ?></address>
        </div>
    </div>
    <div class="col-2">
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('Shipping Method') ?></h2>
            <div class="box-content">
        <?php if ($_order->getShippingDescription()): ?>
            <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
        <?php else: ?>
            <?php echo $this->helper('sales')->__('No shipping information available'); ?>
        <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set">
    <div class="col-1">
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('Billing Address') ?></h2>
            <address class="box-content"><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
    </div>
    <div class="col-2">
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('Payment Method') ?></h2>
            <div class="box-content"><?php echo $this->getPaymentInfoHtml() ?></div>
        </div>
    </div>
</div>
</div>
