<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php
/**
 * - Added grid classes for cross-sell items
 * - Image size changed from 75 to 65
 */
?>

<?php

$theme = $this->helper('ultimo');
//Get list configuration array
$lc = $theme->getCfgGroup('category_list');

//List classes
$listClasses = '';
if ($lc['hover_effect'])
    $listClasses = ' hover-effect';


?>

<?php if($this->getItemCount()): ?>
<div class="crosssell">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <ul id="crosssell-products-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item grid12-6 mobile-grid">
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(145); ?>" width="145" height="145" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
            <div class="product-details">
                <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                <?php if($_item->getRatingSummary()){?>
                    <?php  $rating = $this->getReviewsSummaryHtml($_item, 'short');
                    echo $this->getReviewsSummaryHtml($_item, 'short');
                    if(empty($rating)){?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div style="width:<?php echo $_item->getFeefoReviewsAverage(); ?>%" class="rating"></div>
                            </div>
                        </div>
                    <?php } ?>
                <?php }else{ ?>
                    <div class="ratings">
                        <div class="rating-box">
                            <div style="width:<?php echo $_item->getFeefoReviewsAverage(); ?>%" class="rating"></div>
                        </div>
                    </div>
                <?php } ?>
                <?php echo $this->getPriceHtml($_item, true) ?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
