<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php
/**
 * - Added grid classes for cross-sell items
 * - Image size changed from 75 to 65
 */
?>
<?php if($this->getItemCount()): ?>
<div class="crosssell">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <ul id="crosssell-products-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="allajax-productdatafetch-<?php echo $_item->getId();?> item grid12-6 mobile-grid">
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>"><img class="allajax-imagesfetch-<?php echo $_item->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(160); ?>" width="65" height="65" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
            <div class="product-details">
                <h3 class="product-name allajax-namefetch-<?php echo $_item->getId(); ?>"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_item, true) ?>
                <?php   $product = Mage::getModel('catalog/product')->load($_item->getId());
                        $customcheck = $product->getOptions(); ?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item,array('cart_handle'=> 'true')) ?>','<?php echo $_item->getId();?>','<?php if( $product->getTypeId() == 'simple'&&empty($customcheck) ){ ?>simple<?php }else{ ?>config<?php }?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <ul class="add-to-links addto-gaps-right">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>','<?php echo $_item->getId(); ?>')" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>