<?php
/**
 * @see Enterprise_Reward_Block_Customer_Reward
 */
?>
<div class="dashboard">
    <?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('reward-points', array('label'=>'Reward Points', 'title'=>'Reward Points'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>

<div class="page_wrap ext-reward">
<div class="page_content">


    <h2 class="page_title page_title_gray"><?php echo $this->__('Reward Points') ?></h2>

<div class="my-rewards">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('', true, true); ?>
    
</div>

</div>
<div class="page_foot"></div>
<div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo Mage::helper('customer')->__('Back') ?></a></p>
</div>
</div>
</div>

<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
/* $j1_6(".page_content").css({'float':'none'});
$j1_6(".my-rewards").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'}); */
</script>