<?php
/**
 * 
 */
?>
<?php // RICH SNIPPETS UPDATE ?>
<span itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
<?php
$_product = $this->getProduct();
$_helper = Mage::helper('feefocache');
$_average = $_product->getFeefoReviewsAverage();
$_count = $_product->getFeefoReviewsCount();
?>
    <?php if ($_average != "" && $_average != 0): ?>
        <?php
        $backgroundPos = $_helper->getRatingsBackground($_average);
        ?>
        <?php // RICH SNIPPETS UPDATE ?>
        <meta itemprop="ratingValue" content="<?php echo $_average; ?>"/>
        <meta itemprop="reviewCount" content="<?php echo $_count; ?>" />
        <meta itemprop="bestRating" content="100"/>
        <meta itemprop="worstRating" content="0"/>
        <div class="ratings">
        <?php if ($_product->getFeefoReviewsAverage() > 0 ):?>
            <div class="rating-box">
                <div class="rating" style="background-position:<?php echo $backgroundPos ?>;"></div>
            </div>
        <?php endif;?>
        <p class="rating-links">
            <a href="<?php echo $_product->getProductUrl() ?>?review=1">
                <?php if($_count > 1):
                    echo $this->__('%d Reviews', $_count);
                else:
                    echo $this->__('%d Review', $_count);
                endif; ?>
            </a>
        </p>
    </div>
<?php endif; ?>
</span>
