<?php if(!empty($tabs)):?>
<div <?php if($this->getClassName()):?>class="<?php echo $this->getClassName()?>"<?php endif;?>>
     <?php foreach ($tabs as $tab):?>
     <div class="tabbertab">
	  	<?php $html = $tab->getHtml()?>
     	<?php if(!empty($html)) :?>
     			<?php if(isset($html['title'])) :?>
     				<h2><?php echo $html['title'];?></h2>
     			<?php endif;?>
     			<?php if(isset($html['content'])) :?>
     				<p><?php echo $html['content'];?></p>
     			<?php endif;?>
     	<?php endif;?>     	
     </div>
	<?php endforeach;?>
 </div>
<?php endif;?>