
<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Account_Redeem
 */
?>
<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('gift-card', array('label'=>'Gift Card', 'title'=>'Gift Card'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>

<div class="page_wrap ext-gifcardaccount-redeem" >
<div class="page_content" >		  

    <h2 class="page_title page_title_gray"><?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card'); ?></h2>

<div class="giftcardaccount">
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form id="giftcard-form" action="<?php echo $this->getUrl('*/*/*') ?>" method="post"<?php if (!$this->canRedeem()): ?> onsubmit="giftCardAccountLookupBalance(); return false;"<?php endif; ?>>
        <div id="giftcard_balance_lookup"></div>
        <div class="fieldset">
            <ul class="form-list">
                <li>
                    <label for="giftcard_code"><?php echo $this->__('Enter gift card code') ?></label>
                    <div class="input-box">
                        <input class="required-entry input-text" id="giftcard_code" name="giftcard_code" value="<?php echo $this->getCurrentGiftcard(); ?>" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set form-buttons btn-only">
<?php if ($this->canRedeem()): ?>
            <button class="button" onclick="giftcardForm.submit()" type="button" value="<?php echo $this->__('Redeem Gift Card') ?>"><span><span><?php echo $this->__('Redeem Gift Card') ?></span></span></button>
<?php endif; ?>
            <button class="button check-gc-status" id="gca_balance_button" type="button" value="<?php echo $this->__('Check status and balance') ?>"><span><span><?php echo $this->__('Check status and balance') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
    var giftcardForm = new VarienForm('giftcard-form');
    function giftCardAccountLookupBalance() {
        new Ajax.Updater('giftcard_balance_lookup', '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck', array('_secure' => true)) ?>', {
            onCreate: function() {
                $('gc-please-wait').show()
            },
            onComplete: function() {
                $('gc-please-wait').hide();
                if ($$('.col-main .messages')) {
                    $$('.col-main .messages').invoke('hide');
                }
            },
            parameters : {giftcard_code : $('giftcard_code').value}
        });
    }
    $('gca_balance_button').observe('click', giftCardAccountLookupBalance);
    //]]>
    </script>
</div>
</div>
<div class="page_foot"></div>
</div>
</div>
<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
/* $j1_6(".page_content").css({'float':'none'});
$j1_6(".giftcardaccount").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'}); */
</script>