<?php /* <div id="Level1Home">
    <div class="teaser1 shadow">
        <div id="slideshow">
            <?php echo $this->getChildHtml('slideshow'); ?>
        </div>
    </div>
</div>
*/ ?>
<div id="Level2Home">
    <div class="teaser2first shadow">
        <div id="Box1">
            <?php echo $this->getChildHtml('banner'); ?>
        </div>
    </div>
</div>

<div id="Level3Home">
    <div class="teaser3first shadow">
        <div id="Box1">
            <?php echo $this->getChildHtml('left'); ?>
        </div>
    </div>

    <div class="teaser3 shadow">
        <div id="Box2">
            <?php echo $this->getChildHtml('middle'); ?>
        </div>
    </div>

    <div class="teaser3 shadow">
        <div id="Box3">
            <?php echo $this->getChildHtml('right'); ?>
        </div>
    </div>
</div>

<?php /*
<div id="Level4Home">
    <div class="teaser4firstNoBg">
        <div id="Box1">
            <h3>THE NEW KOBOLD VK150</h3>

            <div class="image"><a class="video" href="kobold_150.html"><img alt="Vorwerk Kobold 140 Vacuum Cleaner"
                                                                            src="img/promo_play.jpg" border="0"/></a>
            </div>

            <div id="TextBox">
                <p class="body2">Find out more about the new Kobold VK150 Home Cleaning System.<br/><br/>
                    <a class="link-intern-150" href="kobold_150.html">click here</a>
                </p>
            </div>

        </div>
    </div>
    <div id="VerticalLine"></div>
    <div class="teaser4NoBg">
        <div id="Box2">
            <h3>VR FIRMWARE UPDATE</h3>

            <div class="image"><a href="#"><img src="img/vr100_update.jpg" alt="Download the VR100 Update" border="0"
                                                title="VR100 Software Update"/></a></div>

            <div id="TextBox">
                <p class="body2">Version 3.2 is available now. Update your Robot for improved performance!<br/><br/>
                    <a href="robotic_vr100_update.html" class="link-intern-150">Update my Robot</a>
                </p>
            </div>

        </div>
    </div>

    <div class="teaser2 shadow">
        <div id="Box3">


            <div id="TextBox">
                <h3>"<span>One gadget I can't live without!</span>"</h3>
                <h4>Sarah Beeny</h4>

                <p class="body2">TV's property expert Sarah Beeny has lived by Vorwerk for many years. See what she had
                    to say about our products and how they helped with the restoration of Rise Hall.<br/><br/>
                    <a href="testimonials.html" class="link-intern-150">Read More</a>
                </p>
            </div>
        </div>
    </div>

</div>
*/ ?>