<?php
/**
 * @see Mage_Core_Block_Template
 */
?>
<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('send-invitations', array('label'=>'Send Invitations', 'title'=>'Send Invitations'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
		  
<div class="page_wrap" >
<div class="page_content" >
    <h2 class="page_title page_title_gray"><?php echo Mage::helper('enterprise_invitation')->__('Send Invitations') ?></h2>

<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<?php echo $this->getChildHtml('form_before')?>
<?php if ($maxPerSend = (int)Mage::helper('enterprise_invitation')->getMaxInvitationsPerSend()): ?>
<form id="invitationForm" action="" method="post">
    <div class="fieldset">
    <h2 class="legend"><?php echo Mage::helper('enterprise_invitation')->__('Invite your friends by entering their email addresses below'); ?></h2>
        <ul class="form-list">
            <?php $_perRow = ceil($maxPerSend/3); for($_index = 1; $_index <= $maxPerSend; $_index ++): ?>
            <li>
                <label for="email_<?php echo $_index ?>"<?php if ($_index == 1) echo ' class="required"' ?>><?php if ($_index == 1) echo '<em>*</em>' ?><?php echo $_index; ?>:</label>
                <div class="input-box">
                    <input tabindex="<?php echo $_index ?>" name="email[]" id="email_<?php echo $_index ?>" title="<?php echo Mage::helper('enterprise_invitation')->__('Email') ?>" value="" class="<?php if ($_index == 1): ?>required-entry <?php endif;?>input-text validate-email" type="text" />
                </div>
            </li>
            <?php endfor; ?>
        <?php if (Mage::helper('enterprise_invitation')->isInvitationMessageAllowed()): ?>
            <li>
                <label for="message"><?php echo Mage::helper('enterprise_invitation')->__('Message');?>: </label>
                <div class="input-box">
                    <textarea tabindex="<?php echo $_index+1 ?>" name="message" id="message" title="<?php echo Mage::helper('enterprise_invitation')->__('Message') ?>"  class="input-text" rows="5" cols="5"></textarea>
                </div>
            </li>
        </ul>
        <?php endif;?>
    </div>
   <p class="required"><?php echo Mage::helper('enterprise_invitation')->__('* Required Fields') ?></p>
    <div class="buttons-set form-buttons">
        <button class="button" type="submit"><span><span><?php echo Mage::helper('enterprise_invitation')->__('Send Invitations') ?></span></span></button>
    </div>

</form>
<script type="text/javascript">
    var contactForm = new VarienForm('invitationForm', true);
</script>
<?php else:?>
<p><?php echo Mage::helper('enterprise_invitation')->__('You cannot send more invitations'); ?></p>
<?php endif; ?>

</div>
<div class="page_foot"></div>
<div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</div>
</div>
<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
$j1_6(".page_content").css({'float':'none'});
$j1_6(".fieldset").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'});
</script>