<?php
/**
 * @see Enterprise_Invitation_Block_Customer_List
 */
?>
<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('store-credit', array('label'=>'Store Credit', 'title'=>'Store Credit'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
		  
<div class="page_wrap" >
<div class="page_content" >
    <h2 class="page_title page_title_gray"><?php echo Mage::helper('enterprise_invitation')->__('My Invitations'); ?></h2>


<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<?php echo $this->getChildHtml('list_before')?>

<?php if (count($this->getInvitationCollection())): ?>

<table class="data-table" id="invitations-list-table" cellpadding="0">
    <col />
    <col width="100" />
    <thead>
        <tr>
            <th>
                <?php echo Mage::helper('enterprise_invitation')->__('Email'); ?>
            </th>
            <th>
                <?php echo Mage::helper('enterprise_invitation')->__('Status'); ?>
            </th>
        </tr>
    </thead>
    <tbody>

    <?php foreach ($this->getInvitationCollection() as $invitation): ?>
        <tr>
            <td>
                <?php echo $this->htmlEscape($invitation->getEmail()); ?>
            </td>
            <td>
                <?php echo $this->helper('enterprise_invitation')->getInvitationStatusText($invitation);?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('invitations-list-table')</script>

<?php else: ?>

<div id="cookie-notice">
    <ul class="messages"><li class="notice-msg">
        <ul><li><?php echo Mage::helper('enterprise_invitation')->__('There are no sent invitations yet'); ?></li></ul>
    </li></ul>
</div>

<?php endif; ?>

<div class="buttons-set">
    <a href="<?php echo $this->helper('enterprise_invitation')->getCustomerInvitationFormUrl(); ?>" class="button"><span><?php echo $this->__('Send Invitations') ?></span></a>
</div>

</div>
<div class="page_foot"></div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</div>
</div>
<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
$j1_6(".page_content").css({'float':'none'});
//$j1_6(".storecredit").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'});
</script>