<div id="contents" >
<div id="sidebar">
	<?php echo $this->getChildHtml('persistent.left.sidebar') ?>
</div>
<div id="content-col" class="ext-login-content">
	<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('login', array('label'=>'Login or Register', 'title'=>'Login or Register'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
    <div class="page_wrap">
    	<div class="page_content">
    		<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
            	<h2 class="page_title page_title_gray"><?php echo strtoupper($this->__('Login or Register')) ?></h2>
            <?php else: ?>
            	<h2 class="page_title page_title_gray"><?php echo strtoupper($this->__('Login or Register')); ?></h2>
            <?php endif; ?>
    		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    		<div class="page_inner">

    			<div class="col2 loginbox">
    				<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
                        <?php echo $this->getBlockHtml('formkey'); ?>
    				<h3 class="page_section_title"><?php echo $this->__('Registered Users')?></h3>
					<div class="col_content">

						<div class="row">
							<label for="email" class="required"><?php echo $this->__('Email Address*')?></label>
							<input type="text" name="login[username]" placeholder="Email" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" type="text" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>">
							<script>
							var searchForm = new Varien.searchForm('login-form', 'email', 'Email');
							</script>
						</div>
						<div class="row">
							<label for="pass" class="required"><?php echo $this->__('Password*')?></label>
							<input name="login[password]" type="password" placeholder="Enter your password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
							<!--[if gte IE 9]>
								<script>
									var searchForm = new Varien.searchForm('login-form', 'pass', 'Enter your password');
								</script>
							<![endif]-->
							<!--[if gte IE 8]>
								<script>
									var searchForm = new Varien.searchForm('login-form', 'pass', 'Enter your password');
								</script>
							<![endif]-->

						</div>
						<?php echo $this->getChildHtml('persistent.remember.me'); ?>
						<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
						<div class="button-row">
							<button type="submit" name="send" id="send2"><?php echo $this->__('Login') ?></button>
						</div>
						<!-- GVAC-366 -->
						 <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
					</div>
                    </form>
    			</div>

    			<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
    			<div class="col2 right registerbox">
    				<h3 class="page_section_title"><?php echo $this->__('New Users') ?> <a rel="lightbox" class="iframelightbox tradecustomer" href="https://godfreysvacuums.wufoo.com/embed/m7p4k1/"><?php echo $this->__('Trade Customer? CLICK HERE') ?></a></h3>
					<div class="col_content">
						<?php echo $this->getChildHtml('customer_form_register2'); ?>

                    </div>
    			</div>
    			<?php endif; ?>
				<div class="clear"></div>
    		</div>
    	</div>
    	<div class="page_foot"></div>
    </div>





        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>

    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //$j1_6(".col-main").css({'padding':'0'});
        /* $j1_6(".col2 a").css({'position':'relative','bottom':'-10px'});
        $j1_6(".register-link").css({'bottom':'-3px','position':'absolute'});
        $j1_6(".page_content").css({'padding-bottom':'10px'});
        $j1_6(".page_inner").css({'height':'175px'}); */
    //]]>
    </script>
</div>
</div>