<div class="customer-account-login">
<div id="contents" >
<div id="sidebar">
	<?php echo $this->getChildHtml('persistent.left.sidebar') ?>
</div>
<div id="content-col" class="ext-login-content">
	<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('login', array('label'=>'Login or Register', 'title'=>'Login or Register'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
    <div class="page_wrap">
    	<div class="page_content">
    		<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
            	<h2 class="page_title page_title_gray"><?php echo strtoupper($this->__('Login or Register')) ?></h2>
            <?php else: ?>
            	<h2 class="page_title page_title_gray"><?php echo strtoupper($this->__('Login or Register')); ?></h2>
            <?php endif; ?>
    		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    		<div class="page_inner">
    			
    			<div class="col2 loginbox">
    				<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
    				<h3 class="page_section_title"><?php echo $this->__('Registered Users')?></h3>
					<div class="col_content">
						
						<div class="row">
							<label for="email" class="required"><?php echo $this->__('Email Address*')?></label>
							<input type="text" name="login[username]" placeholder="Email" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" type="text" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>">
							<script>
							var searchForm = new Varien.searchForm('login-form', 'email', 'Email');
							</script>
						</div>
						<div class="row">
							<label for="pass" class="required"><?php echo $this->__('Password*')?></label>
							<input name="login[password]" type="password" placeholder="Enter your password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
							<!--[if gte IE 9]>
								<script>
									var searchForm = new Varien.searchForm('login-form', 'pass', 'Enter your password');
								</script>
							<![endif]-->
							<!--[if gte IE 8]>
								<script>
									var searchForm = new Varien.searchForm('login-form', 'pass', 'Enter your password');
								</script>
							<![endif]-->
							
						</div>
						<?php echo $this->getChildHtml('persistent.remember.me'); ?>
						<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
						<div class="button-row">
							<button type="submit" name="send" id="send2"><?php echo $this->__('Login') ?></button>    
						</div>
						<!-- GVAC-366 -->
						 <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
					</div>
                    </form>
    			</div>
    			
    			<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
    			<div class="col2 right registerbox">
    				<h3 class="page_section_title"><?php echo $this->__('New Users') ?> <a rel="lightbox" class="iframelightbox tradecustomer" href="https://godfreysvacuums.wufoo.com/embed/m7p4k1/"><?php echo $this->__('Trade Customer? CLICK HERE') ?></a></h3>
					<div class="col_content">
						<div class="account-create">
   
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" placeholder="Email" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
						<script>
							var searchForm = new Varien.searchForm('form-validate', 'email_address', 'Email Address');
							var searchForm = new Varien.searchForm('form-validate', 'firstname', 'First Name');
							var searchForm = new Varien.searchForm('form-validate', 'lastname', 'Last Name');
						</script>
                    </div>
                </li>
                
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
     
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />
                        </div>
                    </div>
                </li>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                    </div>
                </li>
            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                    </div>
                </li>
            <?php endfor ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <div class="fieldset">
        
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" placeholder="Password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" placeholder="Confirm Password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
					
					<!--[if gte IE 9]>
						<script type='text/javascript'>  
							var searchForm = new Varien.searchForm('form-validate', 'password', 'Password');
							var searchForm = new Varien.searchForm('form-validate', 'confirmation', 'Confirm Password');
						</script>
					<![endif]-->
					<!--[if gte IE 8]>
						<script type='text/javascript'>  
							var searchForm = new Varien.searchForm('form-validate', 'password', 'Password');
							var searchForm = new Varien.searchForm('form-validate', 'confirmation', 'Confirm Password');
						</script>
					<![endif]-->
					
						
					
                </li>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
				<?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('SIGN UP FOR the Vacspare newsletter') ?></label>
                </li>
                <?php endif ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
        <div class="buttons-set">
            <button type="submit" title="<?php echo $this->__('Register') ?>" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
						
                    </div>
    			</div>
    			<?php endif; ?>
				<div class="clear"></div>
    		</div>
    	</div>
    	<div class="page_foot"></div>      
    </div>

    
    
    
        
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //$j1_6(".col-main").css({'padding':'0'});        
        /* $j1_6(".col2 a").css({'position':'relative','bottom':'-10px'});
        $j1_6(".register-link").css({'bottom':'-3px','position':'absolute'});
        $j1_6(".page_content").css({'padding-bottom':'10px'});
        $j1_6(".page_inner").css({'height':'175px'}); */
    //]]>
    </script>
</div>
</div>
</div>