<div id="store-locator-panel">
 <div class="inner">
  	<span>To find your nearest Godfreys store simply enter your suburb or postcode.</span>
    <div class="dotted"></div>
      <form id="store-locator-form2">
        <input type="text" value="Suburb or Postcode..." onfocus="if (this.value==this.defaultValue) this.value = ''" onblur="if (this.value=='') this.value = this.defaultValue" />
             <span><a href="#">VIC</a> | <a href="#">NSW</a> | <a href="#">QLD</a> | <a href="#">WA</a> | <a href="#">SA</a><br>
		     <a href="#">NT</a> | <a href="#">TAS</a> | <a href="#">ACT</a></span>
             <button type="submit">Locate</button>
     </form>
 </div>
</div>