<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('billing-agreements', array('label'=>'Billing Agreements', 'title'=>'Billing Agreements'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
		  
<?php /* @var $this Mage_Sales_Block_Billing_Agreements */ ?>
<div class="page_wrap ext-billing" >
<div class="page_content" >

    <h2 class="page_title page_title_gray"><?php echo $this->__('Billing Agreements') ?></h2>


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="billing-agreements">
    <?php $billingAgreements = $this->getBillingAgreements(); ?>
    <?php if (count($billingAgreements) > 0): ?>
        <?php echo $this->getChildHtml('pager'); ?>
        <table id="billing-agreements" class="data-table">
            <col />
            <col width="1" />
            <col />
            <col />
            <col />
            <col width="1" />
            <thead>
                <tr>
                    <th><span class="nobr"><?php echo $this->__('Reference ID'); ?></span></th>
                    <th><?php echo $this->__('Status'); ?></th>
                    <th><span class="nobr"><?php echo $this->__('Created At'); ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('Updated At'); ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('Payment Method'); ?></span></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($billingAgreements as $item): ?>
                <tr>
                    <td><span class="nobr"><?php echo $this->getItemValue($item, 'reference_id') ?></span></td>
                    <td><?php echo $this->getItemValue($item, 'status') ?></td>
                    <td><span class="nobr"><?php echo $this->getItemValue($item, 'created_at') ?></span></td>
                    <td><span class="nobr"><?php echo $this->getItemValue($item, 'updated_at') ?></span></td>
                    <td><?php echo $this->getItemValue($item, 'payment_method_label') ?></td>
                    <td><a href="<?php echo $this->getItemValue($item, 'edit_url') ?>"><?php echo $this->__('View') ?></a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('billing-agreements')</script>
    <?php else: ?>
        <p><?php echo $this->__('There are no billing agreements yet.')?></p>
    <?php endif; ?>

    <?php $paymentMethods = $this->getWizardPaymentMethodOptions() ?>
    <?php if ($paymentMethods): ?>
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('New Billing Agreement') ?></h2>
            <form action="<?php echo $this->getCreateUrl() ?>" method="post">
                <div class="box-content">
                    <p><?php echo $this->__('You will be redirected to the payment system website.') ?></p>
                    <ul class="form-list">
                        <li>
                            <select id="payment_method" name="payment_method">
                                <option value=""><?php echo $this->__('-- Please Select --') ?></option>
                                <?php foreach ($paymentMethods as $code => $title): ?>
                                    <option value="<?php echo $code ?>"><?php echo $title ?></option>
                                <?php endforeach; ?>
                            </select>
                            <button type="submit" class="button"><span><span><?php echo $this->__('Create...') ?></span></span></button>
                        </li>
                    </ul>
                </div>
            </form>
        </div>
    <?php endif; ?>    
</div>

</div>
<div class="page_foot"></div>
<div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</div>
</div>
<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
/* $j1_6(".page_content").css({'float':'none'});
$j1_6(".billing-agreements").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'}); */
</script>