<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('newsletter-subscription', array('label'=>'Newsletter Subscription', 'title'=>'Newsletter Subscription'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
		  
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page_wrap ext-customer-newsletter" >
<div class="page_content" >

    <h2 class="page_title page_title_gray"><?php echo $this->__('Newsletter Subscription') ?></h2>
<div class="page_inner">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Newsletter Subscription') ?></h2>
        <ul class="form-list">
            <li class="control"><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label></li>
        </ul>
    </div>
  	
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
</div>
</div>
<div class="page_foot"></div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
    /* $j1_6(".page_content").css({'float':'none'});
    $j1_6(".page_inner").css({'height':'100px'}); */
//]]>
</script>
