<?php $items = $this->getItems();?>
<?php if(count($items)): ?>
<div class="box-collateral box-up-sell">
    <div class="box-title">
        <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    </div>
    <ul class="products-grid" id="upsell-product-list">
	<?php foreach ($items as $_link) :?>
            <li class="item">
                <a href="<?php echo $_link->getProductUrl() ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
                <?php echo $this->getReviewsSummaryHtml($_link) ?>
                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
            </li>
	<?php endforeach;?>
    </ul>
    <script type="text/javascript">decorateList('upsell-product-list', 'none-recursive')</script>
</div>
<?php endif ?>
