<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('my-tags', array('label'=>'My Tags', 'title'=>'My Tags'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="page_wrap ext-tag-view-page-content" >
<div class="page_content" >

    <h2 class="page_title page_title_gray"><?php echo $this->__('My Tags') ?></h2>

<?php if($this->getTags()): ?>
    <p style="padding-left:20px; padding-top:10px"><?php echo $this->__('Click on a tag to view your corresponding products.') ?></p>
    <ul class="tags-list">
        <?php foreach ($this->getTags() as $_tag): ?>
            <li><a href="<?php echo $this->getUrl('tag/customer/view', array('tagId' => $_tag->getTagId())) ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p style="padding-left:20px; padding-top:10px"><?php echo $this->__('You have not tagged any products yet.') ?></p>
<?php endif; ?>


</div>
<div class="page_foot"></div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</div>
</div>
<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
/* $j1_6(".page_content").css({'float':'none'});
$j1_6(".tags-list").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'}); */
</script>