<div class="col2_container col2_container_address">
    <div class="col2">
        <dl>
            <dt><?php echo $this->__('Billing Information') ?> </dt>
            <dd>
                <?php echo $this->getPrimaryBillingAddressHtml() ?>
            </dd>
        </dl>
        <a class="edit-link" href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a>
    </div>
    <div class="col2 right">
        <dl>
            <dt><?php echo $this->__('Shipping Information') ?></dt>
            <dd>
                <?php echo $this->getPrimaryShippingAddressHtml() ?>
            </dd>
        </dl>
        <a class="edit-link" href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a>
    </div>
</div>   
                 
                           