<?php
/**
 * @category    design
 * @package     enterprise_default
 */
?>
<div class="opc-wrapper">
<div class="page_title page_title_gray" style="margin-bottom:10px;">
    <h2><?php echo $this->__('Register Your Warranty') ?></h2>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<div class="opc-progress-container" id="col-right-opcheckout">
        <?php echo $this->getChildHtml('warrantyProgress') ?>
    </div>
	
	<!--<div class="breadcrumbs-container">
	<?php /*$breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('warranty', array('label'=>'Register your Warranty', 'title'=>'Register your Warranty'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();*/?>
	</div>-->

<ol class="opc" id="registrationSteps">
<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
    <li id="wr-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div class="step-title">
            <span class="number"><?php echo $i ?></span>
            <h2><?php echo $_stepInfo['label'] ?></h2>
            <!--<a href="#"><?php echo $this->__('Edit') ?></a>-->
        </div>
        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
            <?php echo $this->getChildHtml($_stepId) ?>  
        </div>
    </li>
<?php endforeach ?>
</ol>
<script type="text/javascript">
//<![CDATA[
    // Prevents them from opening
    Object.extend(Accordion.prototype, {
      sectionClicked: function(event) {
        return false;
      }
    });
    var accordion = new Accordion('registrationSteps', '.step-title', false);
    
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('wr-<?php echo $this->getActiveStep() ?>');
    $('progress-<?php echo $this->getActiveStep() ?>').addClassName('complete');
    $('progress-login').removeClassName('complete');
    <?php endif ?>
//]]>
</script>
</div>