<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('recurring-profiles', array('label'=>'Recurring Profiles', 'title'=>'Recurring Profiles'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
<?php /* @var $this Mage_Sales_Block_Recurring_Profiles */ ?>

<div class="page_wrap ext-recurring" >
<div class="page_content" >


    <h2 class="page_title page_title_gray"><?php echo $this->__('Recurring Profiles') ?></h2>


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="recurring-profiles">

    <?php echo $this->getChildHtml('grid')?>

    
</div>

</div>
<div class="page_foot"></div>
<div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</div>
</div>
<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
/* $j1_6(".page_content").css({'float':'none'});
$j1_6(".recurring-profiles").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'}); */
</script>