<?php if ($this->isPossibleOnepageCheckout()):?>
	 <a href="javascript:void(0)" class="checkout-link-large" onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">CHECKOUT</a>
     <!--<button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="test" <?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
-->
<?php endif?>
