<div id="onestepcheckout-login-popup" style="display: none;">
    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-contents">
            <div id="onestepcheckout-login-popup-contents-forgot" style="display: none;">
                <h1><?php echo $this->__('Forgotten your password?'); ?></h1>                
                <p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
                <form id="onestepcheckout-forgot-form">
                    <div id="onestepcheckout-forgot-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
                    <div id="onestepcheckout-forgot-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>
                    <div id="onestepcheckout-forgot-success" style="display: none;">
                    <p><?php echo $this->__('We have now sent you a new password to your email address'); ?></p>    
                    </div>

                    <table id="onestepcheckout-forgot-table">
                        <tr>
                            <td>
                                <label for="id_onestepcheckout_email"><?php echo $this->__('Email address'); ?></label>
                            </td>
                         </tr>
                         <tr>   
                            <td>
                                <input type="text" class="input-text required-entry validate-email" name="onestepcheckout_email" id="id_onestepcheckout_email" />
                            </td>
                         </tr>
                         <tr>   
                            <td>
                                <button class="button" id="onestepcheckout-forgot-button" type="button"><span><span><?php echo $this->__('Send password'); ?></span></span></button>
	                            <p class="forgot-pass"><a href="javascript:void(0);" id="onestepcheckout-return-login-link"><?php echo $this->__('Return to Login'); ?></a></p>
                            </td>
                        </tr>
                    </table>
                </form>

            </div>

            <div id="onestepcheckout-login-popup-contents-login">
                <h1><?php echo $this->__('Login'); ?></h1>
                <p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
            
           

            <form id="onestepcheckout-login-form">
                <div id="onestepcheckout-login-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
                <div id="onestepcheckout-login-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>
                    <table id="onestepcheckout-login-table">
                        <tr>
                            <td style="width: 30%;"><label for="id_onestepcheckout_username"><?php echo $this->__('Email address'); ?></label></td>
                        </tr>
                        <tr>
                            <td style="width: 51%;">
                            <input tabindex="100" type="text" class="input-text required-entry validate-email" name="onestepcheckout_username" id="id_onestepcheckout_username" /></td>
                        </tr>

                        <tr>
                            <td><label for="id_onestepcheckout_password"><?php echo $this->__('Password'); ?></label></td>
                        </tr>
                        <tr>   
                            <td><input type="password" tabindex="101" name="onestepcheckout_password" class="input-text required-entry" id="id_onestepcheckout_password" /></td>
                        </tr>
                        <tr>    
                            <td rowspan="2"  style="width: 19%; vertical-align: middle;"><button class="button" tabindex="102" id="onestepcheckout-login-button" type="button"><span><span><?php echo $this->__('Login'); ?></span></span></button>
	                            <p class="forgot-pass"><a href="javascript:void(0);" id="onestepcheckout-forgot-password-link"><?php echo $this->__('Forgot your password?'); ?></a></p>
                            </td>
                        </tr>
                    </table>
                </form>




            </div>        
        </div>
    </div>
    <div class="onestepcheckout-popup-footer">&nbsp;</div>
</div>


 <script type="text/javascript">
    //<![CDATA[
        //var onestepcheckoutforgotform = new VarienForm('onestepcheckout-forgot-form');
        //var onestepcheckoutloginform  = new VarienForm('onestepcheckout-login-form');
    //]]>
</script>



<script>
var onestepcheckout_login_popup;
var login_popup;
Event.observe(window, 'load', function() {
    var options = {
        forgot_password_url: '<?php echo $this->getUrl('onestepcheckout/ajax/forgotPassword', array('_secure'=>true)); ?>',
        login_url: '<?php echo $this->getUrl('onestepcheckout/ajax/login', array('_secure'=>true)); ?>',
        translations: {
            invalid_email: '<?php echo $this->__('Please enter a valid email address'); ?>',
            email_not_found: '<?php echo $this->__('Please enter a registered email address.'); ?>'
        }
    };
    onestepcheckout_login_popup = new OneStepCheckoutLoginPopup(options);
    login_popup = onestepcheckout_login_popup;
});
</script>
