<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('my-orders', array('label'=>'My Orders', 'title'=>'My Orders'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
<div class="page_wrap" >
<div class="page_content" >		  
<?php  $_order = $this->getOrder() ?>
<h2 class="page_title page_title_gray"><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h2>
<div class="order-page">

    
<div class="title-buttons">    
<?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul>
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><strong><?php echo $_link->getLabel() ?></strong></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set">
    <div class="col-1">
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('Shipping Address') ?></h2>
            <address class="box-content"><?php echo $_order->getShippingAddress()->format('html') ?></address>
        </div>
    </div>
    <div class="col-2">
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('Shipping Method') ?><?php /* | <a href="#"><?php echo $this->__('Track Order') ?></a>*/ ?></h2>
            <div class="box-content">
        <?php if ($_order->getShippingDescription()): ?>
            <?php echo $_order->getShippingDescription() ?>
        <?php else: ?>
            <?php echo $this->helper('sales')->__('No shipping information available'); ?>
        <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set">
    <div class="col-1">
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('Billing Address') ?></h2>
            <address class="box-content"><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
    </div>
    <div class="col-2">
        <div class="info-box">
            <h2 class="box-title"><?php echo $this->__('Payment Method') ?></h2>
            <div class="box-content"><?php echo $this->getPaymentInfoHtml() ?></div>
        </div>
    </div>
</div>
</div>

</div>
<div class="page_foot"></div>
</div>
</div>
<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
$j1_6(".page_content").css({'float':'none'});
$j1_6(".order-page").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'});
</script>
