<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>

<p class="wordpress-home-image" ><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('blog_home_image')->toHtml(); ?></p>
<?php /*if ($this->isFirstPage() && $this->getTagLine()): ?>
	<p class="blog-desc blog-tag-line"><?php echo $this->escapeHtml($this->getTagLine()) ?></p>
<?php endif;*/ ?>
<div class="blog-home">
	<?php echo $this->getPostListHtml() ?>
</div>
