<ol <?php if ($this->getCollapsed() && !$this->getHasSelection()): ?>style="display:none" <?php endif ?>>
	<?php $show = ($this->getItemsCount() > 1 || !Mage::getStoreConfig('amshopby/general/hide_one_value')) ?>
	<?php if (0 == $this->getDisplayType() && $show): // default ?>
	<?php foreach ($this->getItems() as $_item): ?>
	<li>
		<?php if ($_item->getCount() > 0): ?>
		<a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
		<?php endif; ?>
		(<?php echo $_item->getCount() ?>) </li>
	<?php endforeach ?>
	<?php elseif (1 == $this->getDisplayType() && $show): // dropdown ?>
	<li>
		<select onchange="if (this.value) setLocation(this.value)" class="amshopby-select">
			
			<option value=""></option>
			<?php foreach ($this->getItems() as $_item): ?>
			<option  <?php if (Mage::app()->getRequest()->getParam('price') == $_item->getValue()) echo "selected" ?> 
                value="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?> (<?php echo $_item->getCount() ?>)</option>
			<?php endforeach ?>
		</select>
	</li>
	<?php elseif (3 == $this->getDisplayType()): // slider ?>
	<?php
    $max = $this->_filter->getMaxPriceInt(); 
    $from = min($this->getPriceFrom(), $max);
    $to   = min($this->getPriceTo(), $max);
    
    if ($from < 0.01 && $to < 0.01){
        $to = sprintf('%.02f', $max);
    }
    $width = 170;
    
    $firstOffset =  $from * $width / $max;
    $secondOffset = $to * $width / $max; 
?>
	<script type="text/javascript">
	jQuery(document).ready(function() {
		
	
		jQuery( "#slider" ).slider({
			range: true,
			min: 0,
			max: <?php echo $max ?>,
			<?php if (is_numeric($from)): ?>
			values: [ <?php echo $from ?>, <?php echo $to ?> ],
			<?php else: ?>
			values: [ 0, <?php echo $to ?> ],
			<?php endif ?>
			slide: function( event, ui ) {
				jQuery( "#amshopby-price-from" ).val( ui.values[ 0 ] );
				jQuery( "#amshopby-price-to" ).val( ui.values[ 1 ] );
				jQuery( "#amount-min" ).text( "$" + ui.values[ 0 ]);
				jQuery( "#amount-max" ).text( "$" + ui.values[ 1 ]); }
		});
		jQuery( "#amshopby-price-from" ).val( jQuery( "#slider" ).slider( "values", 0 ));
		jQuery( "#amshopby-price-to" ).val( jQuery( "#slider" ).slider( "values", 1 ));
		jQuery( "#amount-min" ).text( "$" + jQuery( "#slider" ).slider( "values", 0 ));
		jQuery( "#amount-max" ).text( "$" + jQuery( "#slider" ).slider( "values", 1 ));
		
		
		<?php if($max == '0'): ?>
		// Hides price box
		jQuery( "#narrow-by-list dt.price").hide(); 
		jQuery( "#narrow-by-list dd.price").hide(); 
		<?php endif ?>
		
		
		});
		
	</script>
	<li>
		<div id="slider"></div>
		<div id="amount-min"></div>
		<div id="amount-max"></div>
	</li>
	<?php endif; ?>
	<?php if (Mage::getStoreConfig('amshopby/general/price_from_to')):?>
	<?php if (2 != $this->getDisplayType()):?>
	<?php endif ?>
	<li>
		<input type="text" size="2" value="<?php echo $this->getPriceFrom()?>" name="price_from" class="input-text" id="amshopby-price-from" style="display:none;" />
		<input type="text" size="2" value="<?php echo $this->getPriceTo()?>" name="price_to" class="input-text" id="amshopby-price-to" style="display:none;" />
		<button type="submit" title="<?php echo $this->__('Find')?>" class="form-button button amshopby-price-find" name="price_find" id="amshopby-price-btn"><span><span><?php echo $this->__('Find')?></span></span></button>
	</li>
	<?php endif ?>
	<li style="display:none">
		<input type="hidden" id="amshopby-price-url" value="<?php echo Mage::helper('amshopby/url')->getFullUrl(array('price'=>'price-from,price-to'))?>" />
	</li>
</ol>
