<?php
$_helper = $this->helper('catalog/output');
$theme = $this->helper('ultimo');
$helpLabels = $this->helper('ultimo/labels');
$helpTemplate = $this->helper('ultimo/template');
$helpImg = $this->helper('infortis/image');
$gc = $theme->getCfgGroup('category_grid');
$imgWidth = 295;
$imgHeight = 295;
$lazy = false;

$sku = $this->getSku();
$_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $sku);
if($_product):
?>
<div class="product">
    <div class="product-image-wrapper" style="max-width:<?php echo $imgWidth; ?>px;">



        <?php //Add-to links
        if ($theme->getCfg('category_grid/display_addtolinks') != 0
            && $theme->getCfg('category_grid/addtolinks_simple'))
        {
            if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
            {
                echo $helpTemplate->getCategoryAddtoLinksComplex_2(
                    $_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage visible-onhover');
            }
            else //Always display
            {
                echo $helpTemplate->getCategoryAddtoLinksComplex_2(
                    $_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage');
            }
        }
        ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">

            <?php if ($lazy): ?>
                <img class="lazyOwl" data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
            <?php else: ?>
                <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
            <?php endif; ?>

            <?php if ($theme->getCfg('category/alt_image')): ?>
                <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
            <?php endif; ?>

            <?php echo $helpLabels->getLabels($_product); //Product labels ?>
        </a>

    </div> <!-- end: product-image-wrapper -->

    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
    <?php echo $this->getPriceHtml($_product, true) ?>
    <div class="actions">
        <?php if($_product->isSaleable()): ?>

            <?php if ($this->getHideButton() == false): ?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>','<?php echo $_product->getTypeId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <?php endif; ?>

        <?php else: ?>

            <?php if ($this->getHideButton() == false): ?>
                <p class="availability instore-only"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>

        <?php endif; ?>

        <?php //Add-to links
        if ($theme->getCfg('category_grid/display_addtolinks') != 0 && !$theme->getCfg('category_grid/addtolinks_simple'))
        {
            if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
                echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons display-onhover');
            else //Always display
                echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons');
        }
        ?>
    </div>
</div>
<?php endif;?>