<?php
/**
 * @see Balance_Warranty_Block_Registration_Widget_Dob
 */
?>
<link rel=stylesheet href="/js/jquery/jquery-ui-1.8.17.custom.css" type="text/css">
<script>
	jQuery(function($) {
		function populateDate(dateText){
        var pieces = dateText.split("/");
        $("#day").val(pieces[1]);
        $("#month").val(pieces[0]);
        $("#year").val(pieces[2]);
    }
	jQuery( "#day,#month,#year" ).datepicker({onSelect: populateDate});

	});
</script>

<label for="<?php echo $this->getFieldId('month')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>>
	<?php if ($this->isRequired()) echo '<em>*</em>' ?>
	<?php echo $this->__('Date of Purchase') ?></label>
<div class="input-box customer-dob date-of-purchase">
	<?php
    $this->setDateInput('d',
        '<span class="dob-day dop-day">
             <input type="text" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="input-text validate-custom" ' . $this->getFieldParams() . ' />
             <label for="' . $this->getFieldId('day') . '">' . $this->__('DD') . '</label>
         </span>'
    );

    $this->setDateInput('m',
        '<span class="dob-month dop-month">
             <input type="text" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="input-text validate-custom" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('month') . '">' . $this->__('MM')  . '</label>
         </span>'
    );

    $this->setDateInput('y',
        '<span class="dob-year dop-year">
             <input type="text" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="input-text validate-custom" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('year') . '">' . $this->__('YYYY')  . '</label>
         </span>'
    );
?>
	<?php echo $this->getSortedDateInputs() ?> <span class="dob-full" style="display:none;">
	<input type="hidden" id="<?php echo $this->getFieldId('full')?>" name="<?php echo $this->getFieldName('dob')?>" />
	</span>
	<div class="validation-advice" id="<?php echo $this->getFieldId('date-advice')?>" style="opacity:0.999999; display:none;"></div>
</div>
<script type="text/javascript">
//<![CDATA[
var customer_dob = new Varien.DateElement('id', '<?php echo $this->getFieldId('')?>', <?php echo ($this->isRequired() ? 'true' : 'false'); ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script> 
