<?php if($this->getCollection()->getSize()): ?>
<div class="pagination">
    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <span class="searchresult">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Products %s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <?php echo $this->__('%s Products found', $this->getTotalNum()) ?>
            <?php endif; ?>
        </span>
		<?php if( 0 && $this->isEnabledViewSwitcher() ): ?>
        <p class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <label><?php echo $this->__('View as') ?>:</label>
            <?php $_i=1; $_fix=''; foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if ($_i==1 && strtolower($_code)=='list') $_fix='-fix'; ?>
                <?php if($this->isModeActive($_code)): ?>
                    <strong class="<?php echo strtolower($_code); echo $_fix; ?>" title="<?php echo $_label ?>"><?php echo $_label ?></strong>
                <?php else: ?>
                    <a class="<?php echo strtolower($_code); echo $_fix; ?>" title="<?php echo $_label ?>" href="<?php echo $this->getModeUrl($_code) ?>"><?php echo $_label ?></a>
                <?php endif; ?>
            <?php $_i++; endforeach; ?>
            <?php endif; ?>
        </p>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <?php echo $this->getPagerHtml() ?>
    <?php if ($this->isExpanded()): ?>
        <div class="sort">
			<div class='selectstylesheild'>
				<span class='selectstylesheild-text'>
					<?php $flat="false"; ?>
					<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
						<?php if($this->isOrderCurrent($_key) && trim($this->__($_order))!='Position'): ?>
							<?php echo $this->__($_order) ?>
							<?php $flat="true"; ?>
						<?php endif; ?>
					<?php endforeach; ?>
					<?php 
						if($flat=="false"){echo "Sort By";}
					?>
				</span>
				<select onchange="setLocation(this.value)">
					<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
						<?php if(trim($this->__($_order)) != 'Position'): ?>
						<option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
							<?php echo $this->__($_order) ?>
						</option>
						<?php else: ?>
						<option value=""<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
							<?php echo $this->__('') ?>
						</option>
						<?php endif; ?>
					<?php endforeach; ?>
				</select>
				<span class='selectstylesheild-icon'>&nbsp;</span>
			</div>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>"><img src="<?php echo $this->getSkinUrl('images/sortarrow_rev.png') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
            <?php else: ?>
                <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>"><img src="<?php echo $this->getSkinUrl('images/sortarrow.png') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    </div>

<?php endif ?>
