<?php if($this->isEnabled()):?>
<!-- Google Code for <?php echo $this->getLabel() ?> Conversion Page -->
<script>
/* <![CDATA[ */
var google_conversion_id = <?php echo $this->getConversionId() ?>;
var google_conversion_language = "<?php echo $this->getLanguage() ?>";
var google_conversion_format = "3";
var google_conversion_color = "<?php echo $this->getColor() ?>";
var google_conversion_label = "<?php echo $this->getLabel() ?>";
<?php if ($this->getValue()): ?>
    var google_conversion_value = <?php echo $this->getValue(); ?>;
<?php endif; ?>
var google_conversion_currency = "NZD";
var google_remarketing_only = false;
/* ]]> */
</script>
<script src="<?php echo $this->getConversionUrl() ?>"></script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" border="0" alt="" src="//www.googleadservices.com/pagead/conversion/<?php echo $this->getConversionId() ?>/?value=0.00&currency_code=AUD&label=<?php echo $this->getLabel() ?>&guid=ON&script=0">
    </div>
</noscript>
<?php endif; ?>
