<!-- Warehouse -->
<?php $helper = Mage::helper('warehouse') ?>
<!-- End Warehouse -->

<div class="block block-progress opc-block-progress">

    	<h2 class="side_title_gray"><?php echo $this->__('Checkout Progress') ?></h2>

    <div class="block-content">
        <dl>
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('billing', 'complete')): ?>
            <dt class="complete">
                <?php echo $this->__('Billing Address') ?> <span class="separator">|</span> <a href="#billing" onclick="checkout.accordion.openSection('opc-billing'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <address><?php echo $this->getBilling()->format('html')?></address>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Billing Address') ?>
            </dt>
            <dd>
            	<small><?php echo $this->__('No Details');?></small>
            </dd>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('shipping', 'complete')): ?>
            <dt class="complete">
                <?php echo $this->__('Shipping Address') ?> <span class="separator">|</span> <a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <address><?php echo $this->getShipping()->format('html') ?></address>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Shipping Address') ?>
            </dt>
            <dd>
            	<small><?php echo $this->__('No Details');?></small>
            </dd>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
            <dt class="complete">
                <?php echo $this->__('Shipping Method') ?> <span class="separator">|</span> <a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                
                <!-- Warehouse -->
                <?php /* if ($this->getShippingMethod()): ?>
                    <?php echo $this->getShippingDescription() ?>

                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo $this->__('Shipping method has not been selected yet') ?>
                <?php endif; */ ?>
                <?php if ($helper->getConfig()->isInformationVisible()) : ?>
                <dl class="warehouse-shipping-methods">
                    <?php foreach ($this->getShippingAddresses() as $shippingAddress) : ?>
                    <?php $warehouse = $shippingAddress->getWarehouse() ?>
                    <?php if ($warehouse) : ?>
                    <dt>
                        <a href="#"<?php if ($warehouse->getDescription()) : ?> title="<?php echo $warehouse->getDescription() ?>"<?php endif; ?>>
                            <?php echo $warehouse->getTitle() ?>
        				</a>
                    </dt>
                    <?php endif; ?>
                    <dd>
                        <?php if ($shippingAddress->getShippingMethod()): ?>
                        <?php echo $shippingAddress->getShippingDescription() ?>
                        <?php $_excl = $this->formatPrice($shippingAddress->getShippingAmount()); ?>
                        <?php $_incl = $this->formatPrice($shippingAddress->getShippingInclTax()); ?>
                        <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?><?php echo $_incl; ?>
                        <?php else: ?><?php echo $_excl; ?><?php endif; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>
                        <?php else: ?>
                        <?php if ($warehouse) : ?>
                        <?php echo sprintf($helper->__('Shipping method has not been selected for the %s warehouse yet'), $warehouse->getTitle()) ?>
                        <?php else : ?>
                        <?php echo $this->__('Shipping method has not been selected yet') ?>
                        <?php endif; ?>
                        <?php endif; ?>
                    </dd>
                    <?php endforeach; ?>
                </dl>
                <?php endif; ?>
                <!-- End Warehouse -->
                
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Shipping Method') ?>
            </dt>
            <dd>
            	<small><?php echo $this->__('No Details');?></small>
            </dd>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('payment', 'complete')): ?>
            <dt class="complete">
                <?php echo $this->__('Payment Method') ?> <span class="separator">|</span> <a href="#payment" onclick="checkout.accordion.openSection('opc-payment'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <?php echo $this->getPaymentHtml() ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Payment Method') ?>
            </dt>
            <dd>
            	<small><?php echo $this->__('No Details');?></small>
            </dd>
        <?php endif; ?>
        <?php endif; ?>
        </dl>
    </div>
    <div class="box-foot"></div>
</div>
<?php echo $this->getChildHtml('orderReview', true, true);?>
