<div class="nav-col">
	<h3>About The Site</h3>
    	<ul>
    		<li><a href="#">Site Map</a></li>
    		<li><a href="<?php echo Mage::getBaseUrl().'vacuum-repairs'?>"><?php echo Mage::getModel('cms/page')->load('vacuum-repairs', 'identifier')->getTitle()?></a></li>
    		<li><a href="<?php echo Mage::getBaseUrl().'servicing-your-vacuum'?>"><?php echo Mage::getModel('cms/page')->load('servicing-your-vacuum', 'identifier')->getTitle()?></a></li>
        	<li><a href="<?php echo Mage::getBaseUrl().'exchange-returns'?>"><?php echo Mage::getModel('cms/page')->load('exchange-returns', 'identifier')->getTitle()?></a></li>
        	<li><a href="<?php echo Mage::getBaseUrl().'delivery-information'?>"><?php echo Mage::getModel('cms/page')->load('delivery-information', 'identifier')->getTitle()?></a></li>
            <li><a href="<?php echo Mage::getBaseUrl().'product-warranties'?>"><?php echo Mage::getModel('cms/page')->load('product-warranties', 'identifier')->getTitle()?></a></li>
            <li><a href="<?php echo Mage::getBaseUrl().'privacy-policies'?>"><?php echo Mage::getModel('cms/page')->load('privacy-policies', 'identifier')->getTitle()?></a></li>
            <li><a href="<?php echo Mage::getBaseUrl().'terms-and-conditions'?>"><?php echo Mage::getModel('cms/page')->load('terms-and-conditions', 'identifier')->getTitle()?></a></li>
       	</ul>
</div>

<div class="nav-col">
	<h3>About Us</h3>
     	<ul>
        	<li><a href="<?php echo Mage::getBaseUrl().'company-information'?>"><?php echo Mage::getModel('cms/page')->load('company-information', 'identifier')->getTitle()?></a></li>
            <li><a href="<?php echo Mage::getBaseUrl().'our-services'?>"><?php echo Mage::getModel('cms/page')->load('our-services', 'identifier')->getTitle()?></a></li>
            <li><a href="https://www.onetest.com.au/godfreyscareers/">Godfreys Careers</a></li>
       	</ul>
        
        <h3>Support</h3>
        	<ul>
            	<li><a href="<?php echo Mage::getBaseUrl().'contact-us'?>"><?php echo Mage::getModel('cms/page')->load('contact-us', 'identifier')->getTitle()?></a></li>
                <li><a href="#">Find a Store</a></li>
                <li><a href="#">Register Your Warranty</a></li>
                <li><a href="<?php echo Mage::getBaseUrl().'asthma-allergy-sufferers'?>"><?php echo Mage::getModel('cms/page')->load('asthma-allergy-sufferers', 'identifier')->getTitle()?></a></li>
            	<li><a href="<?php echo Mage::getBaseUrl().'pet-owners'?>"><?php echo Mage::getModel('cms/page')->load('pet-owners', 'identifier')->getTitle()?></a></li>
        	</ul>
</div>