<div id="brands-new">
	<ul>
         <li><img src="<?php echo $this->getSkinUrl('images/b1.png')?>" alt=""></li>
         <li><img src="<?php echo $this->getSkinUrl('images/b2.png') ?>" alt=""></li>
         <li><img src="<?php echo $this->getSkinUrl('images/b3.png') ?>" alt=""></li>
         <li><img src="<?php echo $this->getSkinUrl('images/b4.png') ?>" alt=""></li>
         <li><img src="<?php echo $this->getSkinUrl('images/b5.png') ?>" alt=""></li>
         <li><img src="<?php echo $this->getSkinUrl('images/b6.png') ?>" alt=""></li>
         <li><img src="<?php echo $this->getSkinUrl('images/b7.png') ?>" alt=""></li>
         <li><img src="<?php echo $this->getSkinUrl('images/b8.png') ?>" alt=""></li>
         <li><img src="<?php echo $this->getSkinUrl('images/b9.png') ?>" alt=""></li>
 	</ul>
</div>