<div class="footer-container">
    <div id="footer">
    	<div id="bottom-nav" class="left-col">
	    	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout_single_page_links')->toHtml() ?>
	    </div>
	    <div id="footer-right" class="right-col">
	    	<div class="logo">godfreys</div>
			<div class="footer_logo_img"></div>
	    </div>
        
        <!--<div style="float:right; margin-top:-150px"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('security-image-footer')->toHtml() ?></div>-->
        
        <div id="copyright"><?php echo $this->getCopyright() ?></div>
    </div>
    
</div>
<script type="text/javascript">
	// $j1_6(".footer-container").css({'padding':'0px'});
</script>



<!-- Google Code for Main List -->
<!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 1000400781;
    var google_conversion_label = "NajBCIOjmA8Qjc-D3QM";
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/1000400781/?value=0&amp;label=NajBCIOjmA8Qjc-D3QM&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>