<?php
/**
 * Flint Technology Ltd
 *
 * This module was developed by Flint Technology Ltd (http://www.flinttechnology.co.uk).
 * For support or questions, contact us via http://www.flinttechnology.co.uk/store/contacts
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA bundled with this package in the file LICENSE.txt.
 * It is also available online at http://www.flinttechnology.co.uk/store/module-license-1.0
 *
 * @package     flint_feefo-ee-1.8-1.2.1.zip
 * @registrant  Siobhan Delatai
 * @license     E2C53A03-4603-414C-ABF5-EAD8A60F290E
 * @eula        Flint Module Single Installation License (http://www.flinttechnology.co.uk/store/module-license-1.0
 * @copyright   Copyright (c) 2012 Flint Technology Ltd (http://www.flinttechnology.co.uk)
 */

?>
<?php if (Mage::getStoreConfig('flint_feefo/product/active')):
    $product = Mage::registry('current_product');
    $helper = Mage::helper('flint_feefo/Data');
    $_averageHelper = Mage::helper('feefocache');
    if($dom = $helper->getReviews($product)):
        $feedbacks = $_averageHelper->getFeedback($product);
        ?>
        <div class="box-collateral box-tags product-reviews">
            <div class="reviews-title">
                <h2>Product Reviews</h2>
		        <p>By customers who purchased the <?php echo $product->getName(); ?>.</p>
            </div>

            <div class="std" id="feefo_product_reviews_block">
                <?php if($feedbacks->length):
                     $_productReviewsInfo = $_averageHelper->getRatingsAverage("product", $product);
                    $_serviceReviewsInfo = $_averageHelper->getRatingsAverage("service", $product);
                ?>
                    <table class="data-table" id="product-feefo-reviews">
                        <colgroup><col width="10%"><col></colgroup>
                        <thead>
                            <tr>
                                <th colspan="2">
                                    Average Rating - Rated <?php echo $_productReviewsInfo['average']; ?> out of 5 based out of <?php echo $_productReviewsInfo['count']; ?> votes
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                   <?php
                    $i = 0;
                    foreach($feedbacks as $feedback){
                        $productRating = $_averageHelper->getSingleReview($feedback, "product");
                        ?>
                        <tr>
                            <td>
                                <div class="star-ratings" style="background: url(<?php echo $this->getSkinUrl('images/godfreys_stars.png') ?>) <?php echo $productRating['background']; ?>">&nbsp;</div>
                            </td>
                            <td>
                                <font id="shortCus<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>"><?php echo $productRating['comment']; ?></font>
                                <div class="reviewDate"><?php echo $productRating['date']; ?></div>
                            </td>
                        </tr>
                    <?php } ?>
                            <tr>
                                <td colspan="3">
                                    <a class="read-all-reviews" href="<?php echo 'http://www.feefo.com/feefo/viewvendor.jsp?logon='.$helper->getConfig()->getConfigData('flint_feefo/general/logon'); ?>" onclick="popWin('<?php echo 'http://www.feefo.com/feefo/viewvendor.jsp?logon='.$helper->getConfig()->getConfigData('flint_feefo/general/logon'); ?>', '<?php echo $this->__("Feefo reviews")?>', 'width=1000, height=600, toolbar=no, location=no, scrollbars=1'); return false;">
                                        <?php print(Mage::helper('flint_feefo')->__('View all Reviews')); ?>
                                    </a>
                                </td>
                            <tr>
                        </tbody>
                    </table>
                    <script type="text/javascript">decorateTable('product-feefo-reviews')</script>
                <?php else: ?>
                   <table class="data-table" id="product-feefo-reviews">
                       <tr>
                           <th>
                               <?php echo  $this->__('This product has no reviews yet.'); ?>
                           </th>
                       </tr>
                   </table>
                   <script type="text/javascript">decorateTable('product-feefo-reviews')</script>
                <?php endif; ?>
            </div>
            <?php if($helper->getConfig()->getConfigData('flint_feefo/product/googleStars')):
               $summary = $dom->getElementsByTagName('SUMMARY')->item(0); ?>
               <span style="display:none" class="hreview-aggregate">
                  <span class="item"><span class="fn">Feefo reviews</span></span>
                  <span class="rating"><?php echo $summary->getElementsByTagName('AVERAGE')->item(0)->nodeValue; ?>%</span>
                  <span class="count"><?php echo $summary->getElementsByTagName('TOTALPRODUCTCOUNT')->item(0)->nodeValue; ?></span>
                </span>
            <?php endif; ?>
        </div>
        <div class="box-collateral box-tags service-reviews">
            <div class="reviews-title">
                <h2>Service Reviews</h2>
                <p>By customers who purchased the <?php echo $product->getName(); ?>.</p>
            </div>

            <div class="std" id="feefo_service_reviews_block">
                <?php if($feedbacks->length): ?>
                <table class="data-table" id="service-feefo-reviews">
                    <colgroup><col width="10%"><col></colgroup>
                    <thead>
                        <tr>
                            <th colspan="2">
                                Average Rating - Rated <?php echo $_serviceReviewsInfo['average']; ?> out of 5 based out of <?php echo $_serviceReviewsInfo['count']; ?> votes
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i = 0;
                    foreach($feedbacks as $feedback){
                        $serviceRating = $_averageHelper->getSingleReview($feedback, "service");
                        ?>
                        <tr>
                            <td>
                                <div class="star-ratings" style="background: url(<?php echo $this->getSkinUrl('images/godfreys_stars.png'); ?>) <?php echo $serviceRating['background']; ?>">&nbsp;</div>
                            </td>
                            <td>
                                <font id="shortCus<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue; ?>"><?php echo $serviceRating['comment']; ?></font>
                                <div class="reviewDate"><?php echo $serviceRating['date']; ?></div>
                            </td>
                        </tr>
                    <?php
                    }
                    ?>
                    <tr>
                        <td colspan="3">
                            <a class="read-all-reviews" href="<?php echo 'http://www.feefo.com/feefo/viewvendor.jsp?logon='.$helper->getConfig()->getConfigData('flint_feefo/general/logon'); ?>" onclick="popWin('<?php echo 'http://www.feefo.com/feefo/viewvendor.jsp?logon='.$helper->getConfig()->getConfigData('flint_feefo/general/logon'); ?>', '<?php echo $this->__("Feefo reviews")?>', 'width=1000, height=600, toolbar=no, location=no, scrollbars=1'); return false;">
                                <?php print(Mage::helper('flint_feefo')->__('View all Reviews')); ?>
                            </a>
                        </td>
                    <tr>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('service-feefo-reviews')</script>
                <?php
                else:
                ?>
                    <table class="data-table" id="service-feefo-reviews">
                        <tr>
                            <th>
                                <?php echo  $this->__('This product has no reviews yet.'); ?>
                            </th>
                        </tr>
                    </table>
                    <script type="text/javascript">decorateTable('service-feefo-reviews')</script>
                <?php
                endif;
                ?>
            </div>
            <?php
            if($helper->getConfig()->getConfigData('flint_feefo/product/googleStars')):

                $summary = $dom->getElementsByTagName('SUMMARY')->item(0); ?>
                <span style="display:none" class="hreview-aggregate">
                      <span class="item"><span class="fn">Feefo reviews</span></span>
                      <span class="rating"><?php echo $summary->getElementsByTagName('AVERAGE')->item(0)->nodeValue; ?>%</span>
                      <span class="count"><?php echo $summary->getElementsByTagName('TOTALPRODUCTCOUNT')->item(0)->nodeValue; ?></span>
                    </span>
            <?php endif; ?>
        </div>
    <?php else: ?>
        <h2><?php echo $this->__('FeeFo Reviews') ?><img style="float:right" src="<?php echo $helper->getStarsSrc($product)?>" /></h2>

            <div class="std" id="feefo_reviews_block">
                <?php echo  $this->__('Connection problem to Feefo server.'); ?>
            </div>
    <?php endif; ?>
<?php endif; ?>

