<div id="categories" class="sidebar-box">
            	<h2>Shop by</h2>
                <div id="categories_list">
                	<h3>Vacuum Type</h3>
                    <ul>
                    	<li><a href="#" class="active">Bagless <span>(24)</span></a></li>
						<li><a href="#">Bagged <span>(34)</span></a></li>
						<li><a href="#">Handheld/Portable <span>(16)</span></a></li>
						<li><a href="#">Cordless <span>(18)</span></a></li>
						<li><a href="#">Steam <span>(17)</span></a></li>
						<li><a href="#">Battery <span>(21)</span></a></li>
						<li><a href="#">Automatic <span>(11)</span></a></li>
                    </ul>
                    <h3>Brands</h3>
                    <ul>
                    	<li><a href="#" class="active">Sauber <span>(6)</span></a></li>
						<li><a href="#">Miele <span>(10)</span></a></li>
						<li><a href="#">Wertheim <span>(12)</span></a></li>
						<li><a href="#">Hoover <span>(18)</span></a></li>
						<li><a href="#">Electrolux <span>(14)</span></a></li>
						<li><a href="#">Volta <span>(20)</span></a></li>
						<li><a href="#">Pullman <span>(3)</span></a></li>
                    </ul>
                    <h3>Price</h3>
                    <ul>
                    	<li id="slider-gadget">
                        	<div id="slider-range"></div>
                            <input id="amount-left">
                            <input id="amount-right">
                            <div class="clear"></div>
                        </li>
                    </ul>
                    <h3>Level of clean</h3>
                    <ul>
                    	<li><a href="#" class="active">Single Action <span>(6)</span></a></li>
						<li><a href="#">Double Action  <span>(10)</span></a></li>
						<li><a href="#">Triple Action <span>(12)</span></a></li>
                    </ul>
                    <h3>Floor type</h3>
                    <ul>
                    </ul>
                    <h3>House type</h3>
                    <ul>
                    </ul>
                </div>
                <div class="box-foot"></div>
            </div>