<?php
$_product = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
$swatch_attributes = Mage::helper('colorselectorplus')->getSwatchAttributes();
$title = Mage::getStoreConfig('color_selector_plus/colorselectorplusgeneral/title', Mage::app()->getStore());
$hide = Mage::getStoreConfig('color_selector_plus/colorselectorplusgeneral/hidedropdown', Mage::app()->getStore());
?>

<?php if ($_product->isSaleable() && count($_attributes)): ?>
    <dl>
    	<?php foreach($_attributes as $_attribute): ?>
			<?php $_productAttribute = $_attribute->getProductAttribute(); ?>
			
			<?php if(in_array($_productAttribute->getAttributeCode(), $swatch_attributes)): ?>
				<?php $attributeId = $_attribute->getAttributeId(); ?>
       			<dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
                    <label class="required"><?php echo $this->__($_attribute->getLabel()) ?>: </label>
					<?php echo Mage::helper('colorselectorplus')->getSwatchHtml($_productAttribute->getAttributeCode(), $attributeId, $_product); ?>
                    <div class="input-box">
                        <select name="super_attribute[<?php echo $attributeId ?>]" id="attribute<?php echo $attributeId ?>" class="required-entry no-uniform super-attribute-select<?php if($hide == 1) echo ' swatchSelect' ?>">
                            <option><?php echo $this->__('Choose an Option...') ?></option>
                        </select>
                    </div>
                    <div style="display: none;" id="advice-required-entry-attribute<?php echo $attributeId ?>" class="validation-advice"><?php echo $this->__("Please specify the product's option: %s", $this->__($_attribute->getLabel())) ?></div>
              	</dd>
     		<?php else: ?>
        		<dt><label class="required"><em>*</em><?php echo $_attribute->getLabel() ?></label></dt>
        		<dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
            		<div class="input-box">
                		<select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    		<option><?php echo $this->__('Choose an Option...') ?></option>
                  		</select>
              		</div></dd>
   			<?php endif; ?>
    	
    	<?php endforeach; ?>
    	
    </dl>
    
	<script type="text/javascript">
		var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);
		var selecttitle = '<?php echo $title ?>';
    </script>
<?php endif;
