<form action="http://godfreys.us2.list-manage.com/subscribe/post?u=b1893c239f1f9cc0a8629559d&id=1cb56a7f27" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="footer-form" target="_blank">
    <div class="form-subscribe">
    <div class="form-subscribe-header"><?php echo $this->__('join our mailing list')?></div>
        <label for="newsletter"><?php echo $this->__('Receive exclusive deals and all the latest releases.') ?></label>
        <div class="v-fix"><input type="email" value="<?php echo $this->__('Email Address') ?>" name="EMAIL" class="required email" id="mce-EMAIL" onfocus="if (this.value==this.defaultValue) this.value = ''" onblur="if (this.value=='') this.value = this.defaultValue" /></div>
        <button type="submit" class="button" title="<?php echo $this->__('Go') ?>" name="subscribe" id="mc-embedded-subscribe"><span><span><?php echo $this->__('Go') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
//]]>
</script>

