<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
?>
<!--<div class="page-title category-title">
<?php if($this->IsRssCatalogEnable()): ?>
    <a href="<?php echo $this->getRssLink() ?>" title="<?php echo $this->__('Subscribe to RSS Feed') ?>" class="rss-feed"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
<?php endif; ?>
      <h1><?php echo $_helper->categoryAttribute($_category, $this->getCurrentCategory()->getName(), 'name') ?></h1>
	
</div>
<div id="section-banner">
    <img src="<?php echo Mage::getModel('catalog/category')->load($_category->getEntityId())->getImageUrl()?>" alt="">
</div>-->