<?php
    $_productCollection=$this->getLoadedProductCollection();
	
	//Start getting current category details
	$layer = Mage::getSingleton('catalog/layer');
	$_category = $layer->getCurrentCategory();
	$products_display_mode = $_category->getAttributeName();
	//End getting current category details
	
    $_helper = $this->helper('catalog/output');
    $_helperCompare = $this->helper('catalog/product_compare');
    $_haveCompare = $_helperCompare->getItemCount();
?>
<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<!--  <div id="section-banner">
    	<img src="<?php echo $this->getSkinUrl('images/vacuum_banner.jpg')?>" alt="">
    </div>--> 
<?php echo $this->getToolbarHtml() ?><?php echo $this->getAdditionalHtml() ?>
<?php // List mode ?>
<?php 
	//Start checking the mode
	if(!empty($products_display_mode) && !isset($_REQUEST['mode'])){
		if($products_display_mode == '2'){
			$display_mode = 'list';
		}else{
			$display_mode = 'grid';
		}
	}else{
		$display_mode = $this->getMode();
	}
	//End checking the mode ?>
<?php if($display_mode!='grid'): ?>
<?php $_iterator = 0; ?>
<div id="products" class="products-list-new">
	<ul>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
		<li>
			<?php if($_product->getData('shoutout')): ?>
			<div class="shoutout" style="background:url(<?php echo($this->getSkinUrl()); ?>images/dinkus<?php echo $_product->getData('shoutout') ?>.png)"></div>
			<?php endif; ?>
			<?php // Product Image ?>
			<?php $attributeDinkus = Mage::getModel('catalog/product')
				->load($_product->getId())
				->getAttributeText('dinkus');
				print_r($attributeDinkus);
				
			?>
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(166); ?>" width="166" height="166"alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>"></a>
			<?php // Product description ?>
			<div class="product_info">
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" class="product-title" align="left"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
				<p align="left" class="product-description"><?php echo Mage::getModel('catalog/product')->load($_product->getId())->getShortDescription() ?></p>
				<div class="tags" align="left"><?php echo $this->getChildHtml('productTagList')?></div>
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" class="learnmore" align="left">Learn More</a>
				<dl class="product_features">
					<?php if($_product->getData('warranty') == '80'): ?>
					<dd class="warranty-1yr"><img src="/js/spacer.gif" width="60" height="60" title="1 Year Warranty" /></dd>
					<?php endif ?>
					<?php if($_product->getData('warranty') == '81'): ?>
					<dd class="warranty-2yr"><img src="/js/spacer.gif" width="60" height="60" title="2 Year Warranty" /></dd>
					<?php endif ?>
					<?php if($_product->getData('warranty') == '82'): ?>
					<dd class="warranty-3yr"><img src="/js/spacer.gif" width="60" height="60" title="3 Year Warranty" /></dd>
					<?php endif ?>
					<?php if($_product->getData('warranty') == '83'): ?>
					<dd class="warranty-4yr"><img src="/js/spacer.gif" width="60" height="60" title="4 Year Warranty" /></dd>
					<?php endif ?>
					<?php if($_product->getData('warranty') == '84'): ?>
					<dd class="warranty-5yr"><img src="/js/spacer.gif" width="60" height="60" title="5 Year Warranty" /></dd>
					<?php endif ?>
					<?php if($_product->getData('anti_allergy') == '92'): ?>
					<dd class="allergies"><img src="/js/spacer.gif" width="60" height="60" title="Anti-Allergy" /></dd>
					<?php endif ?>
					<?php if($_product->getData('asthma') == '94'): ?>
					<dd class="asthma"><img src="/js/spacer.gif" width="60" height="60" /></dd>
					<?php endif ?>
					<?php if($_product->getData('pet_hair') == '111'): ?>
					<dd class="pets"><img src="/js/spacer.gif" width="60" height="60" /></dd>
					<?php endif ?>
					<?php if($_product->getData('level_of_clean') == '32'): ?>
					<dd class="single-action"><img src="/js/spacer.gif" width="60" height="60" title="Single Action" /></dd>
					<?php endif ?>
					<?php if($_product->getData('level_of_clean') == '33'): ?>
					<dd class="double-action"><img src="/js/spacer.gif" width="60" height="60" title="Double Action" /></dd>
					<?php endif ?>
					<?php if($_product->getData('level_of_clean') == '34'): ?>
					<dd class="triple-action"><img src="/js/spacer.gif" width="60" height="60" title="Triple Action" /></dd>
					<?php endif ?>
				</dl>
			</div>
			<div class="product-moreinfo">
				<div class="reviews" align="left">
					<?php //if($_product->getRatingSummary()): ?>
					<?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
					<?php //endif; ?>
				</div>
				<div class="product_price" align="left"> <?php echo ($_product->getPrice())?$this->getPriceHtml($_product, true):"" ?></div>
				<div class="product-list-view-test">
					<?php if($_product->isSaleable()): ?>
					<!--<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-to-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"></button>--> 
					<a href="javascript:void(0)" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" class="add-to-cart">add to cart</a>
					<?php else: ?>
					<a href="<?php echo $_product->getProductUrl() // echo $this->getUrl('store-locator'); ?>" title="<?php echo $_productNameStripped; ?>" class="moreinfo-link">more info</a>
					<?php if ($_product->getIsSalable()): ?>
					<!-- <p class="availability in-stock"><span><?php //echo $this->__('In stock') ?></span></p>-->
					<?php else: ?>
					<!--  <p class="availability out-of-stock"><span><?php //echo $this->__('Out of stock') ?></span></p>-->
					<?php endif; ?>
					<?php endif; ?>
									<div class="compare-container">
					<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
					<a href="<?php echo $_compareUrl?>">Add to<br />
					Compare</a>
					<?php endif; ?>
					<?php if($_haveCompare > 0): ?>
					<a href="javascript:void(0)" onclick="popWin('<?php echo $this->helper('catalog/product_compare')->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')">Go to Compare</a>
				<?php endif; ?>
				</div>
				</div>
			</div>
			
			<!--  <div class="product-shop">
                <div class="f-fix">
                    <div class="desc std">
                        
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>

                    <?php else: ?>
                        <?php if ($_product->getIsSalable()): ?>
                            <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                </div>
            </div>--> 
		</li>
		<?php $i++; endforeach; ?>
	</ul>
</div>
<script type="text/javascript">decorateList('products-list', 'none-recursive')</script> 
<?php else: ?>
<?php // Grid Mode ?>
<?php $_collectionSize = $_productCollection->count() ?>
<?php $_columnCount = $this->getColumnCount(); ?>
<?php $_columnCount = 4;?>
<div class="clear"></div>
<div id="products" class="products-grid-new">
	<ul>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
		<?php if ($i++%$_columnCount==0): ?>
		<?php endif ?>
		<li>
			<?php if($_product->getData('shoutout')): ?>
			<div class="shoutout" style="background:url(<?php echo($this->getSkinUrl()); ?>images/dinkus<?php echo $_product->getData('shoutout') ?>.png)"></div>
			<?php endif ?>
			
			<?php $dinkusfilename = Mage::getModel('optionimages/images')->getFileNameImageImages($_product->getDinkus()); ?>
			<?php 
				if(isset($dinkusfilename) && $dinkusfilename!='')
				{
					?>
						<img src='<?php echo Mage::getBaseUrl('media').'image_color'.DS.$dinkusfilename; ?>' alt='' class='dinkus' />
					<?php
				}
			?>
			
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(160); ?>" width="160" height="160" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" /></a>
			<?php //if($_product->isNew()):?>
			<?php //endif;?>
			<div class="product_info" align="left"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)" class="product-title"><?php echo Mage::helper('core/string')->truncate($this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name'),60) ?></a> </div>
			<div class="product-moreinfo">
				<?php //if($_product->getRatingSummary()): ?>
				<div class="reviews" align="left"> <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?> </div>
				<?php //endif; ?>
				<div class="product_price" align="left"> <?php echo ($_product->getPrice())?$this->getPriceHtml($_product, true):"" ?> </div>
				<?php if($_product->isSaleable()): ?>
				<!-- <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-to-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"></button>--> 
				<a href="javascript:void(0)" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" class="add-to-cart">add to cart</a>
				<?php else: ?>
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" class="moreinfo-link">more info</a>
				<?php endif; ?>
				<!--<li><a href="javascript:void(0)">Enquire Now</a></li>-->
				<div class="compare-container">
					<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
					<a href="<?php echo $_compareUrl?>">Add to<br />
					Compare</a>
					<?php endif; ?>
					<?php if($_haveCompare > 0): ?>
					<a href="javascript:void(0)" onclick="popWin('<?php echo $this->helper('catalog/product_compare')->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')">Go to Compare</a>
				<?php endif; ?>
			</div>
			</div>
			<a href="<?php echo $_product->getProductUrl() ?>" class="product-view-details" align="left"><?php echo $this->__('View Product Details'); ?></a>
			<!--  <div class="actions">
                <?php if($_product->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php else: ?>
                    <?php if ($_product->getIsSalable()): ?>
                        <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                <?php endif; ?>
                    
            </div>--> 
		</li>
		<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
		<?php endif ?>
		<?php endforeach ?>
	</ul>
</div>
<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script> 
<script type="text/javascript">
    	/* $j1_6(".price").css({'color':'#232323'});
    	$j1_6(".old-price .price").css({'color':'#E50B14'});
    	//$j1_6(".old-price .price").css({'font-size':'18px', 'color':'#232323'});
    	//$j1_6(".product-moreinfo .product_price .price-box .old-price .price").css({'font-size':'18px', 'color':'#232323'});
		//$j1_6(".product-moreinfo .product_price .price-box .regular-price .price").css({'font-size':'18px', 'color':'#232323'});
		
		$j1_6(".special-price .price-label").text('Save');
		$j1_6(".special-price .price-label").css({'font-size':'11px', 'font-weight':'normal','text-transform':'none', 'position':'relative','left':'-2px'});
		//$j1_6(".special-price .price").css({'left':'-105px', 'font-size':'11px', 'font-weight':'normal','text-transform':'none','top':'-14px'});
		$j1_6(".special-price .price").css({'left':'-105px', 'font-size':'11px', 'font-weight':'normal','text-transform':'none'});
		$j1_6(".ratings").css({'margin':'0'});
		$j1_6(".reviews").css({'height':'16px'});
		$j1_6(".more-links li").css({ 'float':'none','padding':'0 0 0 10px!important','margin':'1px 0 0', 'position':'relative','top':'23px'});
		$j1_6(".more-links").css({'right':'10px'});		 */
		
	</script>
<?php endif;?>
<?php echo $this->getToolbarHtml() ?>
<?php endif;?>
<script type="text/javascript">
    function toggleMoreInfo(el, is_true) {        
        if(is_true == 1)
            $j1_6('.'+el).addClass("active");
        else
            $j1_6('.'+el).removeClass("active");
    }
</script>