<?php // RICH SNIPPETS UPDATE ?>
<span itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
<?php if ($this->getReviewsCount()): ?>
    <?php // RICH SNIPPETS UPDATE ?>
    <meta itemprop="ratingValue" content="<?php echo $this->getRatingSummary(); ?>"/>
    <meta itemprop="reviewCount" content="<?php echo $this->getReviewsCount(); ?>" />
    <meta itemprop="bestRating" content="100"/>
    <meta itemprop="worstRating" content="0"/>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <span class="amount"><a href="javascript:void(0)" onclick="$j1_6('a.l3').click();$j1_6(document.body).animate({'scrollTop':$j1_6('a[name=l3-flag]').offset().top}, 2000);" class="go-to-review"><?php echo $this->getReviewsCount() ?> Review<?php if($this->getReviewsCount() > 1){ echo 's';}?></a></span>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="javascript:void(0)" onclick="$j1_6('a.l3').click();$j1_6(document.body).animate({'scrollTop':$j1_6('a[name=l3-flag]').offset().top}, 2000);" class="go-to-review"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>