<?php if($this->getCustomerId() && $this->getHost()): ?>
	<!-- BEGIN: Analytics.Celebros.Product.Click-->
    <script src="http://<?php echo $this->getHost(); ?>/widgets/CelebrosToolbox.js" type="text/javascript"></script>
    <script type="text/javascript">
		function anlxCallback() {}

	    CelebrosAnalytics.customerid  = '<?php echo $this->getCustomerId(); ?>';
	    CelebrosAnalytics.productsku  = '<?php echo $this->getProductId(); ?>';
	    CelebrosAnalytics.productname = '<?php echo $this->getProductName(); ?>';
	    CelebrosAnalytics.productprice = '<?php echo $this->getProductPrice(); ?>';
	    CelebrosAnalytics.websessionid = '<?php echo $this->getWebsessionId(); ?>';
	    CelebrosAnalytics.AI_LogProduct();
    </script>
	<!-- END: Analytics.Celebros.Product.Click-->
<?php endif?>