<?php
/**
 * 
 */
?>
<?php
$_product = $this->getProduct();
?>
<?php if ($_product->getFeefoReviewsAverage() > 0): ?>
    <div class="ratings">
        <?php if ($_product->getFeefoReviewsAverage() > 0 ):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $_product->getFeefoReviewsAverage() ?>%"></div>
            </div>
        <?php endif;?>
        <p class="rating-links">
            <a href="<?php echo $_product->getProductUrl() ?>#feefo_reviews_block"><?php echo $this->__('%d Review(s)', $_product->getFeefoReviewsCount()) ?></a>
            <span class="separator">|</span>
            <a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Add Your Review') ?></a>
        </p>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>

