<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('gift-registry', array('label'=>'Gift Registry', 'title'=>'Gift Registry'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>

<div class="page_wrap ext-giftregistry-list" >
<div class="page_content" >

    <h2 class="page_title page_title_gray"><?php echo Mage::helper('enterprise_giftregistry')->__('Gift Registry'); ?></h2>

<?php $entityCollection = $this->getEntityCollection(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml();?>

<?php if ($entityCollection->getSize()):?>
    <?php echo $this->getChildHtml('pager') ?>
    <table class="data-table" id="giftregistry-table">
        <col />
        <col width="1" />
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo Mage::helper('enterprise_giftregistry')->__('Event'); ?></th>
                <th><span class="nobr"><?php echo Mage::helper('enterprise_giftregistry')->__('Created On'); ?></span></th>
                <th><?php echo Mage::helper('enterprise_giftregistry')->__('Message'); ?></th>
                <th><?php echo Mage::helper('enterprise_giftregistry')->__('Action'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($entityCollection as $item): ?>
                <tr>
                    <td title="<?php echo $this->getEscapedTitle($item)?>"><?php echo $this->helper('core/string')->truncate($this->getEscapedTitle($item), 70)?></td>
                    <td><span class="nobr"><?php echo $this->getFormattedDate($item) ?></span></td>
                    <td><?php echo $this->getEscapedMessage($item)?></td>
                    <td>
                        <span class="nobr">
                            <a href="<?php echo $this->getItemsUrl($item)?>"><?php echo $this->__('Manage Items') ?></a> <span class="separator">|</span>
                            <a href="<?php echo $this->getShareUrl($item)?>"><?php echo $this->__('Share') ?></a> <span class="separator">|</span>
                            <a href="<?php echo $this->getEditUrl($item)?>"><?php echo $this->__('Edit') ?></a> <span class="separator">|</span>
                            <a href="<?php echo $this->getDeleteUrl($item)?>" onclick="return confirm('<?php echo Mage::helper('enterprise_giftregistry')->__('Are you sure you want to delete this gift registry?'); ?>');"><?php echo $this->__('Delete') ?></a>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('giftregistry-table')</script>
    <?php echo $this->getChildHtml('pager') ?>
<?php else:?>
    <p style="padding-left:20px; padding-top:10px"><?php echo Mage::helper('enterprise_giftregistry')->__('There are no created gift registries yet.'); ?></p>
<?php endif;?>

<div class="buttons-set">
    <?php if ($this->canAddNewEntity()):?>
        <button type="button" onclick="setLocation('<?php echo $this->escapeUrl($this->getAddUrl()) ?>')" class="button"><span><span><?php echo $this->__('Add New') ?></span></span></button>
    <?php endif;?>
</div>

</div>
<div class="page_foot"></div>
<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</div>
</div>

<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
/* $j1_6(".page_content").css({'float':'none'});
$j1_6(".giftcardaccount").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'}); */
</script>
