<div class="account desktop">
    <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()){?>
        <a href="<?php echo Mage::getBaseUrl() . 'customer/account/create/?___SID=S';?>">Login</a>/<a href="<?php echo Mage::getBaseUrl() . 'customer/account/create/?___SID=S';?>">Register</a>
    <?php }else{?>
        <a href="<?php echo Mage::getBaseUrl() . 'customer/account/';?>">My Account</a>/<a href="<?php echo Mage::getBaseUrl() . 'customer/account/logout';?>">Logout</a>
    <?php }?>
</div>