<div class="dashboard">
    <?php /* $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('account-dashboard', array('label'=>'Account Dashboard', 'title'=>'Account Dashboard'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); */ ?>

<div class="page_wrap">
<div class="page_content">
        <h2 class="page_title page_title_gray"><?php echo $this->__('Account Dashboard')?></h2>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php //echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="page_inner">
		<div class="account_dashboard_top">
			<div class="account_dashboard_top_left"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('account_dashboard_top')->toHtml() ?></div>
			<div class="account_dashboard_top_right"><a class="view_last_order" href="<?php echo Mage::getBaseUrl() ?>sales/order/history/"><?php echo $this->__('View Last Order')?></a></div>
			<div class="account_dashboard_top_video"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('account_promo')->toHtml() ?></div>
			<div class="clear"></div>
		</div>
    	<?php echo $this->getChildHtml('info') ?>
    	<?php echo $this->getChildHtml('address') ?>
    </div>
    <div class="clear"></div>
    
    
    <?php //echo $this->getChildHtml('info1') ?>
    <?php //echo $this->getChildHtml('info2') ?>
</div>
<div class="page_foot"></div>
</div>
</div>
