<div class="dashboard">
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('store-credit', array('label'=>'Store Credit', 'title'=>'Store Credit'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>
		  
<div class="page_wrap" >
<div class="page_content" >
    <h2 class="page_title page_title_gray"><?php echo $this->__('Store Credit') ?></h2>

<div class="storecredit">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('', true, true); ?>
</div>
</div>
<div class="page_foot"></div>
</div>
</div>
<script type="text/javascript">
//$j1_6(".col-main").css({'padding-right':'20px','padding-left':'0'});;
$j1_6(".page_content").css({'float':'none'});
$j1_6(".storecredit").css({'padding-left':'20px', 'padding-top':'10px','padding-right':'20px'});
</script>