<!--  --><div class="code-box-content-new">
    <h3><?php echo $this->__('Gift Cards') ?></h3>
    <div id="giftcard_balance_lookup"></div>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>    
    <form id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post">
        <fieldset>
            <p for="giftcard_code"><?php echo $this->__('Enter the gift card code') ?></p>
            <div class="v-fix"><input class="required-entry input-text" id="giftcard_code" name="giftcard_code" value="" /></div>
            <button class="button1" onclick="giftcardForm.submit()" type="button" value="<?php echo $this->__('Apply code') ?>"><span><span><?php echo $this->__('Apply code') ?></span></span></button>
            <!--  <button class="button2 check-gc-status" onclick="new Ajax.Updater('giftcard_balance_lookup', '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>', {onCreate: function() { $('gc-please-wait').show() }, onComplete: function() { $('gc-please-wait').hide() }, parameters : {giftcard_code : $('giftcard_code').value}})" type="button" value="<?php echo $this->__('Check gift Card status and balance') ?>"><span><span><?php echo $this->__('Check Gift Card status and balance') ?></span></span></button>
        	-->
        	<a href="javascript:void(0)" onclick="new Ajax.Updater('giftcard_balance_lookup', '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>', {onCreate: function() { $('gc-please-wait').show() }, onComplete: function() { $('gc-please-wait').hide() }, parameters : {giftcard_code : $('giftcard_code').value}})">Check gift Card status and balance</a>
        </fieldset>
    </form>

    <script type="text/javascript">
    //<![CDATA[
    var giftcardForm = new VarienForm('giftcard-form');
    //]]>
    </script>
</div>

