<?php
/**
 * Featured Products Slider
 */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
?>
<?php if ($_productCollection && ($_collectionSize = $this->getCollectionCount())): ?>
    <?php
    $_helper = $this->helper('catalog/output');
    $theme = $this->helper('ultimo');
    $helpLabels = $this->helper('ultimo/labels');
    $helpTemplate = $this->helper('ultimo/template');
    $helpImg = $this->helper('infortis/image');
    $sliderClasses = '';
    $gridClasses = '';

    $sliderId = "itemslider-featured-{$this->getFrontendHash()}";

    //Slider parameters
    //--------------------------------------------------------------

    //Responsive mode on/off
    $isResponsive = $this->getIsResponsive(); //param: is_responsive
    if ($isResponsive === NULL) //Param not set
    {
        $isResponsive = true; //IMPORTANT: enabled by default
    }

    //Assign number of items in a row to specific viewport width
    $breakpoints = $this->getBreakpoints(); //param: breakpoints
    if ($breakpoints === NULL) //Param not set
    {
        $breakpoints = '[0, 1], [320, 2], [480, 3], [768, 4], [960, 5], [1280, 6]'; //Set default breakpoints
    }

    //Number of items in a row displayed if responsive mode is off
    $showItems = $this->getShowItems(); //param: show_items
    if (!$showItems) //Param not set or equals zero
    {
        $showItems = 5; //Set default number of items
    }

    //Pagination on/off
    $pagination = $this->getPagination(); //param: pagination

    //Slider initial delay
    $initDelay = 0;
    $initDelay = intval($this->getInitDelay()); //param: init_delay

    //Image width
    $imgWidth = $this->getImgWidth(); //param: img_width
    if ($imgWidth === NULL) //Param not set
    {
        $imgWidth = 196; //Set default value
    }
    else
    {
        $imgWidth = intval($imgWidth);
    }

    //Image aspect ratio
    if ($theme->getCfg('category/aspect_ratio'))
    {
        $imgHeight = 0; //Keep aspect ratio - height will be calculated automatically based on width
    }
    else
    {
        $imgHeight = $imgWidth; //Don't keep aspect ratio - height is the same as width
    }

    //Image height
    if ($this->getImgHeight() !== NULL) //param: img_height
    {
        //If param is set, it overrides default height and aspect ratio settings
        $imgHeight = intval($this->getImgHeight());
    }

    //Slider timeout. Set to enable automatic scrolling.
    $timeout = $this->getTimeout(); //param: timeout
    if ($timeout === NULL) //Param not set
    {
        $timeout = intval($theme->getCfg('product_slider/timeout'));
    }
    else
    {
        $timeout = intval($timeout);
    }

    //Number of items that should move on scrolling
    $move = $this->getMove(); //param: move
    if ($move === NULL) //Param not set
    {
        $move = 0; //By default scroll all visible items
    }
    else
    {
        $move = intval($move);
    }

    //If set, slider will loop
    $loop = $this->getLoop(); //param: loop
    if ($loop === NULL) //Param not set
    {
        $loop = $theme->getCfg('product_slider/loop');
    }

    //Speed (arrows / touch swipe)
    $speed = intval($theme->getCfg('product_slider/speed'));

    //Speed (automatic scrolling / pagination)
    $autoSpeed = intval($theme->getCfg('product_slider/auto_speed'));

    //Pause slider on mouse hover
    $pause = $theme->getCfg('product_slider/pause');

    //Lazy loading
    $lazy = $theme->getCfg('product_slider/lazy');

    //Slider classes
    //--------------------------------------------------------------
    if($isResponsive)
    {
        $sliderClasses .= ' itemslider-responsive';
    }

    if ($_collectionSize == 1)
    {
        $sliderClasses .= ' single-item';
    }

    //Product grid classes
    //--------------------------------------------------------------
    //Size of grid elements
    $size = $this->getSize(); //param: size
    if ($size)
    {
        $gridClasses = ' ' . $size;
    }
    else
    {
        if ($showItems >= 8)
        {
            $gridClasses = ' size-xs';
        }
        elseif ($showItems >= 6)
        {
            $gridClasses = ' size-s';
        }
    }

    //Align elements to the center
    if ($this->getCentered()) //param: centered
    {
        $gridClasses .= ' centered';
    }

    //Set equal height for all items
    if ($this->getEqualHeight()) //param: equal_height
    {
        $gridClasses .= ' equal-height';
    }
    ?>

    <?php /*<h3 class="section-title padding-right"><?php echo $this->getBlockName(); ?></h3> */?>
    <div class="itemslider-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">
        <div id="<?php echo $sliderId; ?>" class="itemslider<?php if($sliderClasses) echo $sliderClasses; ?> products-grid<?php if($gridClasses) echo $gridClasses; ?>">
            <?php foreach ($_productCollection as $_product): ?>
                <div class="item allajax-productdatafetch-<?php echo $_product->getId(); ?>">
                    <div class="product-image-wrapper" style="max-width:<?php echo $imgWidth; ?>px;">

                        <?php //Add-to links
                        if ($theme->getCfg('category_grid/display_addtolinks') != 0
                            && $theme->getCfg('category_grid/addtolinks_simple'))
                        {
                            if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
                            {
                                echo $helpTemplate->getCategoryAddtoLinksComplex_2(
                                    $_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage visible-onhover');
                            }
                            else //Always display
                            {
                                echo $helpTemplate->getCategoryAddtoLinksComplex_2(
                                    $_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage');
                            }
                        }
                        ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">

                            <?php if ($lazy): ?>
                                <img class="lazyOwl allajax-imagesfetch-<?php echo $_product->getId(); ?>" data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                            <?php else: ?>
                                <img class="allajax-imagesfetch-<?php echo $_product->getId(); ?>" src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                            <?php endif; ?>

                            <?php if ($theme->getCfg('category/alt_image')): ?>
                                <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                            <?php endif; ?>

                            <?php echo $helpLabels->getLabels($_product); //Product labels ?>
                            <?php
                            if($_product->getData('shoutout')): ?>
                                <?php $_dinkus = strtolower($_product->getAttributeText('shoutout'));
                                $_dinkus = str_replace(' ', '-', $_dinkus); ?>
                                <div class="shoutout"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/ultimo/default/images/dinkus/<?php echo $_dinkus ?>.png" alt="<?php echo $_product->getAttributeText('shoutout') ?>" /></div>
                                <!--<div class="shoutout" style="background:url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>/frontend/ultimo/default/images/dinkus/dinkus<?php echo $_product->getData('shoutout') ?>.png')"></div>-->
                            <?php endif; ?>
                        </a>

                    </div> <!-- end: product-image-wrapper -->

                    <h3 class="product-name allajax-namefetch-<?php echo $_product->getId(); ?>"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php if (!$_product->isSaleable() && $_product->getPrice() == 0): ?>
                        <p class="avaibility visit-store-info">
                            <span><?php echo $this->__('Please visit stores for pricing information') ?></span></p>
                    <?php else: ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>

                            <?php if ($_product->getData('online_only')){ ?>
                                <a href="/locator" class="instore-only"><?php echo $this->__('Instore Only') ?></a>
                            <?php }else{ ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId(); ?>','<?php if( $_product->getTypeId() == 'simple'&&empty($customcheck) ){ ?>simple<?php }else{ ?>config<?php }?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php } ?>

                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>

                        <?php //Add-to links
                        if ($theme->getCfg('category_grid/display_addtolinks') != 0 && !$theme->getCfg('category_grid/addtolinks_simple'))
                        {
                            if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
                            echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons display-onhover');
                            else //Always display
                            echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons');
                        }
                        ?>
                    </div>
                <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div> <!-- end: itemslider -->
    </div> <!-- end: itemslider-wrapper -->
    <script type="text/javascript">
        //<![CDATA[
        jQuery(function($) {

            var owl = $('#<?php echo $sliderId; ?>');
            owl.owlCarousel({

                <?php if ($lazy): ?>
                lazyLoad: true,
                <?php endif; ?>

                <?php if(!$isResponsive): ?>
                responsive: false,
                items: <?php echo $showItems; ?>,
                <?php else: ?>
                itemsCustom: [ <?php echo $breakpoints; ?> ],
                responsiveRefreshRate: 50,
                <?php endif; ?>

                <?php if ($speed): ?>
                slideSpeed: <?php echo $speed; ?>,
                <?php endif; ?>

                <?php if ($autoSpeed): ?>
                paginationSpeed: <?php echo $autoSpeed; ?>,
                <?php endif; ?>

                <?php if ($move !== 1): ?>
                scrollPerPage: true,
                <?php endif; ?>

                <?php if ($timeout): ?>
                autoPlay: <?php echo $timeout; ?>,
                <?php endif; ?>

                <?php if ($pause): ?>
                stopOnHover: true,
                <?php endif; ?>

                <?php if ($loop): ?>
                rewindNav: true,
                rewindSpeed: 600,
                <?php else: ?>
                rewindNav: false,
                <?php endif; ?>

                <?php if ($pagination): ?>
                pagination: true,
                <?php else: ?>
                pagination: false,
                <?php endif; ?>

                navigation: true

            }); //end: owl

        });
        //]]>
    </script>
<?php endif; ?>
<?php if (!Mage::registry('balance_slider_allajax')) {
      Mage::register('balance_slider_allajax', '1');
    ?>
<a style="display: none;" id="various1" href="#allajax-content" >Inline</a>


<div style="display: none;">
    <div id="inline1" style="width:300px;height:100px;overflow:auto;">

        <div id="allajax-content" class="allajax-content bbb" >
            <div class="allajax-preload" id="allajax-prestep">
                <a id="ajax-loading-lightbx-pro-image" href="#" title=" " class="product-image" id="">
                    <img src="#" width="128" height="128" alt=" ">
                </a>
                <div class="product-info">
                    <h2 class="product-name" id="ajax-loading-lightbx-pro-name">
                        <a href="#" title=" "> </a>
                    </h2>
                    <div class="ratings" id="ajax-loading-lightbx-pro-rating">

                    </div>
                    <div class="product-type-data"><div class="price-box" id="ajax-loading-lightbx-pro-price-box">

                        </div></div>
                </div>
                <div class="allajax-loading" id="">
                    <img alt="Loading..." src="<?php echo $this->getSkinUrl('balance/allajax/images/loading.gif'); ?>">
                    <span id="add_to_cart">Loading...</span>
                </div>
                <div class="allajax-configurations" id="allajax-configurations-append">

                </div>

            </div>
            <div id="allajax-poststeps">
                <div class="allajax-respond-msg">

                </div>
                <a id="ajax-loading-lightbx-pro-image-respond" href="#" title=" " class="product-image" id="">
                    <img src="#" width="160" height="160" alt=" ">
                </a>

                <div class="product-info">
                    <h2 class="product-name" id="ajax-loading-lightbx-pro-name-respond">
                    </h2>
                    <div class="product-type-data"><div class="price-box" id="ajax-loading-lightbx-pro-price-box-respond">

                        </div></div>
                </div>

                <div class="actions clearer">
                    <button type="button" title="View all items in your shopping cart" class="button btn-inline button-view" id="allajax_view_cart" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>')"><span><span>View cart & checkout</span></span></button>
                    <button type="button" title="View all items in your compare" class="button btn-inline button-view" id="allajax_view_compare" style="display: none" onclick="jQuery.fancybox.close();popWin('<?php echo Mage::helper('catalog/product_compare')->getListUrl(); ?>','compare','top:0,left:0,width=750,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Go to compare') ?></span></span></button>
                    <button type="button" title="Continue Shopping" class="button btn-checkout btn-inline " onclick="jQuery.fancybox.close();"><span><span>Continue Shopping</span></span></button>
                </div>


            </div>
        </div>

    </div>



</div>

<script type="text/javascript">
    <?php $baseUrl = $this->getBaseUrl() ; ?>
    function getBaseUrl() { return '<?php echo $baseUrl; ?>'; }

</script>

<?php }?>
