<form action="http://godfreys.us2.list-manage2.com/subscribe/post?u=b1893c239f1f9cc0a8629559d&amp;id=822e587655" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="footer-form" target="_blank">
    <div id="mailinglist">
    	<h4><?php echo $this->__('join our mailing list')?></h4>
        <div class="v-fix"><input type="email" value="Enter your email address" name="EMAIL" class="required email" id="mce-EMAIL" onfocus="if (this.value==this.defaultValue) this.value = ''" onblur="if (this.value=='') this.value = this.defaultValue" /></div>
        <button type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
//]]>
</script>

