<div class="dashboard">
    <?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
		  $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
		  $breadcrumbs->addCrumb('account-dashboard', array('label'=>'Account Dashboard', 'title'=>'Account Dashboard'));
		  echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>

<div class="page_wrap">
<div class="page_content">
        <h2 class="page_title page_title_gray"><?php echo $this->__('WELCOME')?></h2>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php //echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="page_inner">
    	<h3 class="page_section_title"><?php echo $this->__('Account Information') ?></h3>
    	<?php echo $this->getChildHtml('info') ?>
    	<?php echo $this->getChildHtml('address') ?>
    </div>
    <div class="clear"></div>
    
    
    <?php //echo $this->getChildHtml('info1') ?>
    <?php //echo $this->getChildHtml('info2') ?>
</div>
<div class="page_foot"></div>
</div>
</div>
