<div class="header-container" id="custom_header_container">
    <!-- header s -->
    <div id="header">
        <?php if ($this->getIsHomePage()):?>
            <div id="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></div>
        <?php else:?>
            <div id="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"></a></div>
        <?php endif?>


        <div id="header-right">
            <?php echo $this->getLayout()->getBlock('account.links')->toHtml();?>
            <div id="top-nav" class="custom_head">
                <span>NEED MORE INFORMATION?</span><br />
                <a href="/contact-us">CONTACT US NOW</a>
            </div>
        </div>
    </div>
</div>
<div class="custom_main_container">

<?php
    $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
    $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
    $breadcrumbs->addCrumb('onestepcheckout', array('label'=>'OneStepCheckout', 'title'=>'OneStepCheckout'));
?>