<script type="text/javascript">
// Make all description div heights nice & even (FK)
$j1_6(document).ready(function() {
var maxHeight = 0;
$j1_6('div.description').each(function() { 
	maxHeight = Math.max(maxHeight, $j1_6(this).height()); 
	});
$j1_6('div.description').height(maxHeight);
});
</script>
<script type="text/javascript">
// Make all feature row heights nice & even (FK)
$j1_6(document).ready(function() {
   var maxRows = 0;
    $j1_6('.compare_col').each(function() {
        maxRows = Math.max(maxRows, $j1_6(this).find('td.caption').length)
    })
    for (var i = 0; i < maxRows; i++) {
        var maxHeight = 0;
        $j1_6('.info_chart tr:nth-child(' + i + ') td.col1').each(function() {
            maxHeight = Math.max(maxHeight, $j1_6(this).height())
        })
        $j1_6('.info_chart tr:nth-child(' + i + ') td.col1').each(function() {
            $j1_6(this).height(maxHeight)
        })
    }
})
</script>
<?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');?>
<?php $breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));?>
<?php $breadcrumbs->addCrumb('compare', array('label'=>'Compare', 'title'=>'Compare'));?>
<?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();?>

<div class="wide_page_wrap_compare">
	<div class="wide_page_content_compare" id="compare">
		<h2 class="page_title page_title_gray"><?php echo $this->__('Compare Products') ?></h2>
		<!-- <a href="#" onclick="window.print(); return false;" class="link-print"><?php echo $this->__('Print This Page') ?></a> -->
		
		<?php $_total=$this->getItems()->getSize() ?>
		<?php if($_total): ?>
		<table>
			<tr>
				<?php $_helper = $this->helper('catalog/output'); ?>
				<?php foreach($this->getItems() as $_item): ?>
				<td><div class="compare_col" width="<?php echo floor(100/$_total); ?>%">
						<div class="product_image"> <a class="product-image" href="#" onclick="setPLocation('<?php echo $_item->getProductUrl() ?>', true)" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'image')->resize(250, 250); ?>" width="250" height="250" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" /></a> <a href="#" class="remove" onclick="removeItem('<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>');" title="<?php echo $this->__('Remove Product') ?>"><img src="<?php echo $this->getSkinUrl('images/removebutton.png'); ?>" alt="<?php echo $this->__('Remove Product') ?>" /></a> </div>
						<div class="product-title"><a href="#" onclick="setPLocation('<?php echo $_item->getProductUrl() ?>', true)" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?></a></div>
						<div class="product-reviews"> <?php echo $this->getReviewsSummaryHtml($_item, 'short',true) ?> </div>
						<div class="product_config">
							<div class="product_config_top"></div>
							<div class="product_config_content">
								<input name="qty_<?php echo $_item->getId()?>" id="qty_<?php echo $_item->getId()?>" type="hidden" size="5" value="1">
								<?php /* ?>
				<form name="quantity">
                	<div class="row">
                       	<input name="qty_<?php echo $_item->getId()?>" id="qty_<?php echo $_item->getId()?>" type="text" size="5" value="1">
                       	<label>Quantity</label>
                    </div>                        	
                </form>
				<?php */ ?>
								<div class="product-price"> <?php echo ($_item->getPrice())?$this->getPriceHtml($_item, true, '-compare-list-top'):'<div style="height:14px;"></div>' ?> </div>
								<div class="button-row">
									<?php if($_item->isSaleable()): ?>
									<a href="javascript:void(0)" class="add-to-cart-large" onclick="setPLocation('<?php echo $this->getBaseUrl().'checkout/cart/add?product='.$_item->getId()?>&qty='+document.getElementById('qty_<?php echo $_item->getId()?>').value, true)"><?php echo $this->__('Add to Cart') ?></a>
									<?php else: ?>
									<a href="#" class="moreinfo-link-large">more info</a>
									<?php if ($_item->getIsSalable()): ?>
									<!--  <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>-->
									<?php else: ?>
									<!--<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>-->
									<?php endif; ?>
									<?php endif; ?>
									<a href="javascript:void(0)" class="more-options"></a>
									<ul class="more-links">
										<li><a href="javascript:void(0)">Enquire Now</a></li>
										<li><a href="<?php echo $this->helper('catalog/product_compare')->getAddUrl($_item)?>">Add this item to Compare</a></li>
										<li><a href="javascript:void(0)" onclick="popWin('<?php echo $this->helper('catalog/product_compare')->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')">Go to Compare</a></li>
									</ul>
								</div>
							</div>
							<div class="product_config_bottom"></div>
						</div>
						<div class="description">
							<?php foreach ($this->getAttributes() as $_attribute): ?>
							<?php if($_attribute->getAttributeCode()=="description"):?>
							<p><?php echo $_helper->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?></p>
							<?php elseif($_attribute->getAttributeCode()=="short_description"):?>
							<div class="key_features"> <?php echo $_helper->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?> </div>
							<?php endif; ?>
							<?php endforeach;?>
							<?php if ($_item->getFeature_1() || $_item->getFeature_2() || $_item->getFeature_3()): ?>
							<dt><?php echo $this->__('Features')?></dt>
							<dd>
								<ul class="product-features-top3">
									<?php if($_item->getFeature_1()): ?>
									<li><?php echo $_item->getFeature_1(); ?></li>
									<?php endif ?>
									<?php if($_item->getFeature_2()): ?>
									<li><?php echo $_item->getFeature_2(); ?></li>
									<?php endif ?>
									<?php if($_item->getFeature_3()): ?>
									<li><?php echo $_item->getFeature_3(); ?></li>
									<?php endif ?>
								</ul>
							</dd>
							<?php endif; ?>
						</div>
						<div class="info_chart">
							<table cellpadding="0" cellspacing="0" border="0">
								<?php $i=1;?>
								<?php foreach ($this->getAttributes() as $_attribute): ?>
								<?php if((($_attribute->getAttributeCode()=="short_description")||($_attribute->getAttributeCode()=="description")) && $_helper->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) != 'No' ):?>
								<?php else:?>
								<?php if($i%2==1):?>
								<tr class="odd">
									<?php else:?>
								<tr class="even">
									<?php endif;?>
									<td class="col1"><div id="red-bullet"></div></td>
									<td class="caption"><?php echo $this->__($_attribute->getFrontendLabel()) ?></td>
									<td>
                                        <?php $value = $_helper->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode());
                                        if($value == 'No'):
                                            echo 'N/A';
                                        else:
                                            echo $value;
                                        endif; ?>
                                    </td>
								</tr>
								<?php $i++;?>
								<?php endif;?>
								<?php endforeach;?>
							</table>
						</div>
					</div></td>
				<?php endforeach;?>
			</tr>
		</table>
		<div class="buttons-set"> 
			<!--  <button type="button" class="button" onclick="window.close();"><span><span><?php echo $this->__('Close Window') ?></span></span></button>--> 
			<span class="please-wait" id="compare-list-please-wait" style="display:none;"> <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?> </span> </div>
		<script type="text/javascript">
		//$j1_6(".special-price .price-label").text('Save:');
		
    	decorateTable('product_comparison');

        /**
         * Send remove item request, after that reload windows
         */
        function removeItem(url)
        {
            new Ajax.Request(url, {
                parameters: {isAjax: 1, method: 'POST'},
                onLoading: function(){$('compare-list-please-wait').show();},
                onSuccess: function(transport) {
                    $('compare-list-please-wait').hide();
                    window.location.reload();
                    window.opener.location.reload();
                }
            });
        }
    </script>
		<?php else: ?>
		<script type="text/javascript">window.close();</script>
		<?php endif; ?>
	</div>
	<div class="wide_page_foot"></div>
</div>
<script type="text/javascript">
$j1_6('.special-price .price').css({'left':'-35px','top':'-17px'});
</script>
